// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/core/v1/machine.proto

package corev1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineState int32

const (
	MachineState_MachineState_Unknown     MachineState = 0
	MachineState_MachineState_Pending     MachineState = 1
	MachineState_MachineState_Starting    MachineState = 2
	MachineState_MachineState_Running     MachineState = 3
	MachineState_MachineState_Degraded    MachineState = 4
	MachineState_MachineState_Error       MachineState = 5
	MachineState_MachineState_Terminating MachineState = 6
	MachineState_MachineState_Terminated  MachineState = 7
)

// Enum value maps for MachineState.
var (
	MachineState_name = map[int32]string{
		0: "MachineState_Unknown",
		1: "MachineState_Pending",
		2: "MachineState_Starting",
		3: "MachineState_Running",
		4: "MachineState_Degraded",
		5: "MachineState_Error",
		6: "MachineState_Terminating",
		7: "MachineState_Terminated",
	}
	MachineState_value = map[string]int32{
		"MachineState_Unknown":     0,
		"MachineState_Pending":     1,
		"MachineState_Starting":    2,
		"MachineState_Running":     3,
		"MachineState_Degraded":    4,
		"MachineState_Error":       5,
		"MachineState_Terminating": 6,
		"MachineState_Terminated":  7,
	}
)

func (x MachineState) Enum() *MachineState {
	p := new(MachineState)
	*p = x
	return p
}

func (x MachineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineState) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_core_v1_machine_proto_enumTypes[0].Descriptor()
}

func (MachineState) Type() protoreflect.EnumType {
	return &file_baepo_core_v1_machine_proto_enumTypes[0]
}

func (x MachineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineState.Descriptor instead.
func (MachineState) EnumDescriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{0}
}

type MachineDesiredState int32

const (
	MachineDesiredState_MachineDesiredState_Unknown    MachineDesiredState = 0
	MachineDesiredState_MachineDesiredState_Pending    MachineDesiredState = 1
	MachineDesiredState_MachineDesiredState_Running    MachineDesiredState = 2
	MachineDesiredState_MachineDesiredState_Terminated MachineDesiredState = 3
)

// Enum value maps for MachineDesiredState.
var (
	MachineDesiredState_name = map[int32]string{
		0: "MachineDesiredState_Unknown",
		1: "MachineDesiredState_Pending",
		2: "MachineDesiredState_Running",
		3: "MachineDesiredState_Terminated",
	}
	MachineDesiredState_value = map[string]int32{
		"MachineDesiredState_Unknown":    0,
		"MachineDesiredState_Pending":    1,
		"MachineDesiredState_Running":    2,
		"MachineDesiredState_Terminated": 3,
	}
)

func (x MachineDesiredState) Enum() *MachineDesiredState {
	p := new(MachineDesiredState)
	*p = x
	return p
}

func (x MachineDesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineDesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_core_v1_machine_proto_enumTypes[1].Descriptor()
}

func (MachineDesiredState) Type() protoreflect.EnumType {
	return &file_baepo_core_v1_machine_proto_enumTypes[1]
}

func (x MachineDesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineDesiredState.Descriptor instead.
func (MachineDesiredState) EnumDescriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{1}
}

type MachineTerminationCause int32

const (
	MachineTerminationCause_MachineTerminationCause_Unknown           MachineTerminationCause = 0
	MachineTerminationCause_MachineTerminationCause_HealthcheckFailed MachineTerminationCause = 1
	MachineTerminationCause_MachineTerminationCause_ManuallyRequested MachineTerminationCause = 2
	MachineTerminationCause_MachineTerminationCause_InternalError     MachineTerminationCause = 3
	MachineTerminationCause_MachineTerminationCause_NoNodeAvailable   MachineTerminationCause = 4
	MachineTerminationCause_MachineTerminationCause_Expired           MachineTerminationCause = 5
)

// Enum value maps for MachineTerminationCause.
var (
	MachineTerminationCause_name = map[int32]string{
		0: "MachineTerminationCause_Unknown",
		1: "MachineTerminationCause_HealthcheckFailed",
		2: "MachineTerminationCause_ManuallyRequested",
		3: "MachineTerminationCause_InternalError",
		4: "MachineTerminationCause_NoNodeAvailable",
		5: "MachineTerminationCause_Expired",
	}
	MachineTerminationCause_value = map[string]int32{
		"MachineTerminationCause_Unknown":           0,
		"MachineTerminationCause_HealthcheckFailed": 1,
		"MachineTerminationCause_ManuallyRequested": 2,
		"MachineTerminationCause_InternalError":     3,
		"MachineTerminationCause_NoNodeAvailable":   4,
		"MachineTerminationCause_Expired":           5,
	}
)

func (x MachineTerminationCause) Enum() *MachineTerminationCause {
	p := new(MachineTerminationCause)
	*p = x
	return p
}

func (x MachineTerminationCause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineTerminationCause) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_core_v1_machine_proto_enumTypes[2].Descriptor()
}

func (MachineTerminationCause) Type() protoreflect.EnumType {
	return &file_baepo_core_v1_machine_proto_enumTypes[2]
}

func (x MachineTerminationCause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineTerminationCause.Descriptor instead.
func (MachineTerminationCause) EnumDescriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{2}
}

type MachineContainerState int32

const (
	MachineContainerState_MachineContainerState_Unknown MachineContainerState = 0
	MachineContainerState_MachineContainerState_Running MachineContainerState = 1
	MachineContainerState_MachineContainerState_Exited  MachineContainerState = 2
)

// Enum value maps for MachineContainerState.
var (
	MachineContainerState_name = map[int32]string{
		0: "MachineContainerState_Unknown",
		1: "MachineContainerState_Running",
		2: "MachineContainerState_Exited",
	}
	MachineContainerState_value = map[string]int32{
		"MachineContainerState_Unknown": 0,
		"MachineContainerState_Running": 1,
		"MachineContainerState_Exited":  2,
	}
)

func (x MachineContainerState) Enum() *MachineContainerState {
	p := new(MachineContainerState)
	*p = x
	return p
}

func (x MachineContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_core_v1_machine_proto_enumTypes[3].Descriptor()
}

func (MachineContainerState) Type() protoreflect.EnumType {
	return &file_baepo_core_v1_machine_proto_enumTypes[3]
}

func (x MachineContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineContainerState.Descriptor instead.
func (MachineContainerState) EnumDescriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{3}
}

type MachineContainerRestartSpec_Policy int32

const (
	MachineContainerRestartSpec_Policy_Unknown   MachineContainerRestartSpec_Policy = 0
	MachineContainerRestartSpec_Policy_No        MachineContainerRestartSpec_Policy = 1
	MachineContainerRestartSpec_Policy_OnFailure MachineContainerRestartSpec_Policy = 2
	MachineContainerRestartSpec_Policy_Always    MachineContainerRestartSpec_Policy = 3
)

// Enum value maps for MachineContainerRestartSpec_Policy.
var (
	MachineContainerRestartSpec_Policy_name = map[int32]string{
		0: "Policy_Unknown",
		1: "Policy_No",
		2: "Policy_OnFailure",
		3: "Policy_Always",
	}
	MachineContainerRestartSpec_Policy_value = map[string]int32{
		"Policy_Unknown":   0,
		"Policy_No":        1,
		"Policy_OnFailure": 2,
		"Policy_Always":    3,
	}
)

func (x MachineContainerRestartSpec_Policy) Enum() *MachineContainerRestartSpec_Policy {
	p := new(MachineContainerRestartSpec_Policy)
	*p = x
	return p
}

func (x MachineContainerRestartSpec_Policy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineContainerRestartSpec_Policy) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_core_v1_machine_proto_enumTypes[4].Descriptor()
}

func (MachineContainerRestartSpec_Policy) Type() protoreflect.EnumType {
	return &file_baepo_core_v1_machine_proto_enumTypes[4]
}

func (x MachineContainerRestartSpec_Policy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineContainerRestartSpec_Policy.Descriptor instead.
func (MachineContainerRestartSpec_Policy) EnumDescriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{2, 0}
}

type MachineSpec struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Cpus          uint32                  `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryMb      uint64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Containers    []*MachineContainerSpec `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	Timeout       *uint64                 `protobuf:"varint,4,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetCpus() uint32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *MachineSpec) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *MachineSpec) GetContainers() []*MachineContainerSpec {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *MachineSpec) GetTimeout() uint64 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

type MachineContainerSpec struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Name          string                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                           `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Env           map[string]string                `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command       []string                         `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Healthcheck   *MachineContainerHealthcheckSpec `protobuf:"bytes,5,opt,name=healthcheck,proto3" json:"healthcheck,omitempty"`
	WorkingDir    *string                          `protobuf:"bytes,6,opt,name=working_dir,json=workingDir,proto3,oneof" json:"working_dir,omitempty"`
	Restart       *MachineContainerRestartSpec     `protobuf:"bytes,7,opt,name=restart,proto3" json:"restart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineContainerSpec) Reset() {
	*x = MachineContainerSpec{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContainerSpec) ProtoMessage() {}

func (x *MachineContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContainerSpec.ProtoReflect.Descriptor instead.
func (*MachineContainerSpec) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{1}
}

func (x *MachineContainerSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MachineContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MachineContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *MachineContainerSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *MachineContainerSpec) GetHealthcheck() *MachineContainerHealthcheckSpec {
	if x != nil {
		return x.Healthcheck
	}
	return nil
}

func (x *MachineContainerSpec) GetWorkingDir() string {
	if x != nil && x.WorkingDir != nil {
		return *x.WorkingDir
	}
	return ""
}

func (x *MachineContainerSpec) GetRestart() *MachineContainerRestartSpec {
	if x != nil {
		return x.Restart
	}
	return nil
}

type MachineContainerRestartSpec struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Policy        MachineContainerRestartSpec_Policy `protobuf:"varint,1,opt,name=policy,proto3,enum=baepo.core.v1.MachineContainerRestartSpec_Policy" json:"policy,omitempty"`
	MaxRetries    int32                              `protobuf:"varint,2,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineContainerRestartSpec) Reset() {
	*x = MachineContainerRestartSpec{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContainerRestartSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContainerRestartSpec) ProtoMessage() {}

func (x *MachineContainerRestartSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContainerRestartSpec.ProtoReflect.Descriptor instead.
func (*MachineContainerRestartSpec) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{2}
}

func (x *MachineContainerRestartSpec) GetPolicy() MachineContainerRestartSpec_Policy {
	if x != nil {
		return x.Policy
	}
	return MachineContainerRestartSpec_Policy_Unknown
}

func (x *MachineContainerRestartSpec) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type MachineContainerHealthcheckSpec struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InitialDelaySeconds int32                  `protobuf:"varint,1,opt,name=initial_delay_seconds,json=initialDelaySeconds,proto3" json:"initial_delay_seconds,omitempty"`
	PeriodSeconds       int32                  `protobuf:"varint,2,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*MachineContainerHealthcheckSpec_Http
	Type          isMachineContainerHealthcheckSpec_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineContainerHealthcheckSpec) Reset() {
	*x = MachineContainerHealthcheckSpec{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContainerHealthcheckSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContainerHealthcheckSpec) ProtoMessage() {}

func (x *MachineContainerHealthcheckSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContainerHealthcheckSpec.ProtoReflect.Descriptor instead.
func (*MachineContainerHealthcheckSpec) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{3}
}

func (x *MachineContainerHealthcheckSpec) GetInitialDelaySeconds() int32 {
	if x != nil {
		return x.InitialDelaySeconds
	}
	return 0
}

func (x *MachineContainerHealthcheckSpec) GetPeriodSeconds() int32 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

func (x *MachineContainerHealthcheckSpec) GetType() isMachineContainerHealthcheckSpec_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MachineContainerHealthcheckSpec) GetHttp() *MachineContainerHealthcheckSpec_HttpHealthcheckSpec {
	if x != nil {
		if x, ok := x.Type.(*MachineContainerHealthcheckSpec_Http); ok {
			return x.Http
		}
	}
	return nil
}

type isMachineContainerHealthcheckSpec_Type interface {
	isMachineContainerHealthcheckSpec_Type()
}

type MachineContainerHealthcheckSpec_Http struct {
	Http *MachineContainerHealthcheckSpec_HttpHealthcheckSpec `protobuf:"bytes,3,opt,name=http,proto3,oneof"`
}

func (*MachineContainerHealthcheckSpec_Http) isMachineContainerHealthcheckSpec_Type() {}

type MachineEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MachineId string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*MachineEvent_StateChanged
	//	*MachineEvent_Started
	//	*MachineEvent_Terminated
	//	*MachineEvent_DesiredStateChanged
	//	*MachineEvent_ReconciliationStarted
	//	*MachineEvent_ReconciliationCompleted
	//	*MachineEvent_HealthcheckEvent
	Event         isMachineEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineEvent) Reset() {
	*x = MachineEvent{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEvent) ProtoMessage() {}

func (x *MachineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEvent.ProtoReflect.Descriptor instead.
func (*MachineEvent) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{4}
}

func (x *MachineEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MachineEvent) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *MachineEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MachineEvent) GetEvent() isMachineEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MachineEvent) GetStateChanged() *MachineEvent_StateChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*MachineEvent_StateChanged); ok {
			return x.StateChanged
		}
	}
	return nil
}

func (x *MachineEvent) GetStarted() *MachineEvent_StartedEvent {
	if x != nil {
		if x, ok := x.Event.(*MachineEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *MachineEvent) GetTerminated() *MachineEvent_TerminatedEvent {
	if x != nil {
		if x, ok := x.Event.(*MachineEvent_Terminated); ok {
			return x.Terminated
		}
	}
	return nil
}

func (x *MachineEvent) GetDesiredStateChanged() *MachineEvent_DesiredStateChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*MachineEvent_DesiredStateChanged); ok {
			return x.DesiredStateChanged
		}
	}
	return nil
}

func (x *MachineEvent) GetReconciliationStarted() *MachineEvent_ReconciliationStartedEvent {
	if x != nil {
		if x, ok := x.Event.(*MachineEvent_ReconciliationStarted); ok {
			return x.ReconciliationStarted
		}
	}
	return nil
}

func (x *MachineEvent) GetReconciliationCompleted() *MachineEvent_ReconciliationCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*MachineEvent_ReconciliationCompleted); ok {
			return x.ReconciliationCompleted
		}
	}
	return nil
}

func (x *MachineEvent) GetHealthcheckEvent() *MachineEvent_ContainerStateChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*MachineEvent_HealthcheckEvent); ok {
			return x.HealthcheckEvent
		}
	}
	return nil
}

type isMachineEvent_Event interface {
	isMachineEvent_Event()
}

type MachineEvent_StateChanged struct {
	StateChanged *MachineEvent_StateChangedEvent `protobuf:"bytes,4,opt,name=state_changed,json=stateChanged,proto3,oneof"`
}

type MachineEvent_Started struct {
	Started *MachineEvent_StartedEvent `protobuf:"bytes,5,opt,name=started,proto3,oneof"`
}

type MachineEvent_Terminated struct {
	Terminated *MachineEvent_TerminatedEvent `protobuf:"bytes,6,opt,name=terminated,proto3,oneof"`
}

type MachineEvent_DesiredStateChanged struct {
	DesiredStateChanged *MachineEvent_DesiredStateChangedEvent `protobuf:"bytes,7,opt,name=desired_state_changed,json=desiredStateChanged,proto3,oneof"`
}

type MachineEvent_ReconciliationStarted struct {
	ReconciliationStarted *MachineEvent_ReconciliationStartedEvent `protobuf:"bytes,8,opt,name=reconciliation_started,json=reconciliationStarted,proto3,oneof"`
}

type MachineEvent_ReconciliationCompleted struct {
	ReconciliationCompleted *MachineEvent_ReconciliationCompletedEvent `protobuf:"bytes,9,opt,name=reconciliation_completed,json=reconciliationCompleted,proto3,oneof"`
}

type MachineEvent_HealthcheckEvent struct {
	HealthcheckEvent *MachineEvent_ContainerStateChangedEvent `protobuf:"bytes,10,opt,name=healthcheck_event,json=healthcheckEvent,proto3,oneof"`
}

func (*MachineEvent_StateChanged) isMachineEvent_Event() {}

func (*MachineEvent_Started) isMachineEvent_Event() {}

func (*MachineEvent_Terminated) isMachineEvent_Event() {}

func (*MachineEvent_DesiredStateChanged) isMachineEvent_Event() {}

func (*MachineEvent_ReconciliationStarted) isMachineEvent_Event() {}

func (*MachineEvent_ReconciliationCompleted) isMachineEvent_Event() {}

func (*MachineEvent_HealthcheckEvent) isMachineEvent_Event() {}

type MachineContainerHealthcheckSpec_HttpHealthcheckSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) Reset() {
	*x = MachineContainerHealthcheckSpec_HttpHealthcheckSpec{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContainerHealthcheckSpec_HttpHealthcheckSpec) ProtoMessage() {}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContainerHealthcheckSpec_HttpHealthcheckSpec.ProtoReflect.Descriptor instead.
func (*MachineContainerHealthcheckSpec_HttpHealthcheckSpec) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{3, 0}
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type MachineEvent_StateChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         MachineState           `protobuf:"varint,1,opt,name=state,proto3,enum=baepo.core.v1.MachineState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineEvent_StateChangedEvent) Reset() {
	*x = MachineEvent_StateChangedEvent{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineEvent_StateChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEvent_StateChangedEvent) ProtoMessage() {}

func (x *MachineEvent_StateChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEvent_StateChangedEvent.ProtoReflect.Descriptor instead.
func (*MachineEvent_StateChangedEvent) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{4, 0}
}

func (x *MachineEvent_StateChangedEvent) GetState() MachineState {
	if x != nil {
		return x.State
	}
	return MachineState_MachineState_Unknown
}

type MachineEvent_StartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineEvent_StartedEvent) Reset() {
	*x = MachineEvent_StartedEvent{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineEvent_StartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEvent_StartedEvent) ProtoMessage() {}

func (x *MachineEvent_StartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEvent_StartedEvent.ProtoReflect.Descriptor instead.
func (*MachineEvent_StartedEvent) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{4, 1}
}

func (x *MachineEvent_StartedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type MachineEvent_TerminatedEvent struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Cause              MachineTerminationCause `protobuf:"varint,1,opt,name=cause,proto3,enum=baepo.core.v1.MachineTerminationCause" json:"cause,omitempty"`
	TerminationDetails *string                 `protobuf:"bytes,2,opt,name=termination_details,json=terminationDetails,proto3,oneof" json:"termination_details,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MachineEvent_TerminatedEvent) Reset() {
	*x = MachineEvent_TerminatedEvent{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineEvent_TerminatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEvent_TerminatedEvent) ProtoMessage() {}

func (x *MachineEvent_TerminatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEvent_TerminatedEvent.ProtoReflect.Descriptor instead.
func (*MachineEvent_TerminatedEvent) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{4, 2}
}

func (x *MachineEvent_TerminatedEvent) GetCause() MachineTerminationCause {
	if x != nil {
		return x.Cause
	}
	return MachineTerminationCause_MachineTerminationCause_Unknown
}

func (x *MachineEvent_TerminatedEvent) GetTerminationDetails() string {
	if x != nil && x.TerminationDetails != nil {
		return *x.TerminationDetails
	}
	return ""
}

type MachineEvent_DesiredStateChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DesiredState  MachineDesiredState    `protobuf:"varint,1,opt,name=desired_state,json=desiredState,proto3,enum=baepo.core.v1.MachineDesiredState" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineEvent_DesiredStateChangedEvent) Reset() {
	*x = MachineEvent_DesiredStateChangedEvent{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineEvent_DesiredStateChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEvent_DesiredStateChangedEvent) ProtoMessage() {}

func (x *MachineEvent_DesiredStateChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEvent_DesiredStateChangedEvent.ProtoReflect.Descriptor instead.
func (*MachineEvent_DesiredStateChangedEvent) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{4, 3}
}

func (x *MachineEvent_DesiredStateChangedEvent) GetDesiredState() MachineDesiredState {
	if x != nil {
		return x.DesiredState
	}
	return MachineDesiredState_MachineDesiredState_Unknown
}

type MachineEvent_ReconciliationStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DesiredState  MachineDesiredState    `protobuf:"varint,1,opt,name=desired_state,json=desiredState,proto3,enum=baepo.core.v1.MachineDesiredState" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineEvent_ReconciliationStartedEvent) Reset() {
	*x = MachineEvent_ReconciliationStartedEvent{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineEvent_ReconciliationStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEvent_ReconciliationStartedEvent) ProtoMessage() {}

func (x *MachineEvent_ReconciliationStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEvent_ReconciliationStartedEvent.ProtoReflect.Descriptor instead.
func (*MachineEvent_ReconciliationStartedEvent) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{4, 4}
}

func (x *MachineEvent_ReconciliationStartedEvent) GetDesiredState() MachineDesiredState {
	if x != nil {
		return x.DesiredState
	}
	return MachineDesiredState_MachineDesiredState_Unknown
}

type MachineEvent_ReconciliationCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DesiredState  MachineDesiredState    `protobuf:"varint,1,opt,name=desired_state,json=desiredState,proto3,enum=baepo.core.v1.MachineDesiredState" json:"desired_state,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineEvent_ReconciliationCompletedEvent) Reset() {
	*x = MachineEvent_ReconciliationCompletedEvent{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineEvent_ReconciliationCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEvent_ReconciliationCompletedEvent) ProtoMessage() {}

func (x *MachineEvent_ReconciliationCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEvent_ReconciliationCompletedEvent.ProtoReflect.Descriptor instead.
func (*MachineEvent_ReconciliationCompletedEvent) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{4, 5}
}

func (x *MachineEvent_ReconciliationCompletedEvent) GetDesiredState() MachineDesiredState {
	if x != nil {
		return x.DesiredState
	}
	return MachineDesiredState_MachineDesiredState_Unknown
}

func (x *MachineEvent_ReconciliationCompletedEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type MachineEvent_ContainerStateChangedEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerName    string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	State            MachineContainerState  `protobuf:"varint,2,opt,name=state,proto3,enum=baepo.core.v1.MachineContainerState" json:"state,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	ExitedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=exited_at,json=exitedAt,proto3,oneof" json:"exited_at,omitempty"`
	ExitCode         *int32                 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	ExitError        *string                `protobuf:"bytes,6,opt,name=exit_error,json=exitError,proto3,oneof" json:"exit_error,omitempty"`
	Healthy          bool                   `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`
	HealthcheckError *string                `protobuf:"bytes,8,opt,name=healthcheck_error,json=healthcheckError,proto3,oneof" json:"healthcheck_error,omitempty"`
	RestartCount     int32                  `protobuf:"varint,9,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MachineEvent_ContainerStateChangedEvent) Reset() {
	*x = MachineEvent_ContainerStateChangedEvent{}
	mi := &file_baepo_core_v1_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineEvent_ContainerStateChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEvent_ContainerStateChangedEvent) ProtoMessage() {}

func (x *MachineEvent_ContainerStateChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_core_v1_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEvent_ContainerStateChangedEvent.ProtoReflect.Descriptor instead.
func (*MachineEvent_ContainerStateChangedEvent) Descriptor() ([]byte, []int) {
	return file_baepo_core_v1_machine_proto_rawDescGZIP(), []int{4, 6}
}

func (x *MachineEvent_ContainerStateChangedEvent) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *MachineEvent_ContainerStateChangedEvent) GetState() MachineContainerState {
	if x != nil {
		return x.State
	}
	return MachineContainerState_MachineContainerState_Unknown
}

func (x *MachineEvent_ContainerStateChangedEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *MachineEvent_ContainerStateChangedEvent) GetExitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitedAt
	}
	return nil
}

func (x *MachineEvent_ContainerStateChangedEvent) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *MachineEvent_ContainerStateChangedEvent) GetExitError() string {
	if x != nil && x.ExitError != nil {
		return *x.ExitError
	}
	return ""
}

func (x *MachineEvent_ContainerStateChangedEvent) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *MachineEvent_ContainerStateChangedEvent) GetHealthcheckError() string {
	if x != nil && x.HealthcheckError != nil {
		return *x.HealthcheckError
	}
	return ""
}

func (x *MachineEvent_ContainerStateChangedEvent) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

var File_baepo_core_v1_machine_proto protoreflect.FileDescriptor

const file_baepo_core_v1_machine_proto_rawDesc = "" +
	"\n" +
	"\x1bbaepo/core/v1/machine.proto\x12\rbaepo.core.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\vMachineSpec\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\rR\x04cpus\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x04R\bmemoryMb\x12C\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2#.baepo.core.v1.MachineContainerSpecR\n" +
	"containers\x12\x1d\n" +
	"\atimeout\x18\x04 \x01(\x04H\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\"\xa0\x03\n" +
	"\x14MachineContainerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12>\n" +
	"\x03env\x18\x03 \x03(\v2,.baepo.core.v1.MachineContainerSpec.EnvEntryR\x03env\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12P\n" +
	"\vhealthcheck\x18\x05 \x01(\v2..baepo.core.v1.MachineContainerHealthcheckSpecR\vhealthcheck\x12$\n" +
	"\vworking_dir\x18\x06 \x01(\tH\x00R\n" +
	"workingDir\x88\x01\x01\x12D\n" +
	"\arestart\x18\a \x01(\v2*.baepo.core.v1.MachineContainerRestartSpecR\arestart\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_working_dir\"\xdf\x01\n" +
	"\x1bMachineContainerRestartSpec\x12I\n" +
	"\x06policy\x18\x01 \x01(\x0e21.baepo.core.v1.MachineContainerRestartSpec.PolicyR\x06policy\x12\x1f\n" +
	"\vmax_retries\x18\x02 \x01(\x05R\n" +
	"maxRetries\"T\n" +
	"\x06Policy\x12\x12\n" +
	"\x0ePolicy_Unknown\x10\x00\x12\r\n" +
	"\tPolicy_No\x10\x01\x12\x14\n" +
	"\x10Policy_OnFailure\x10\x02\x12\x11\n" +
	"\rPolicy_Always\x10\x03\"\xdd\x03\n" +
	"\x1fMachineContainerHealthcheckSpec\x122\n" +
	"\x15initial_delay_seconds\x18\x01 \x01(\x05R\x13initialDelaySeconds\x12%\n" +
	"\x0eperiod_seconds\x18\x02 \x01(\x05R\rperiodSeconds\x12X\n" +
	"\x04http\x18\x03 \x01(\v2B.baepo.core.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpecH\x00R\x04http\x1a\xfc\x01\n" +
	"\x13HttpHealthcheckSpec\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12i\n" +
	"\aheaders\x18\x04 \x03(\v2O.baepo.core.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04type\"\xda\x0f\n" +
	"\fMachineEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12T\n" +
	"\rstate_changed\x18\x04 \x01(\v2-.baepo.core.v1.MachineEvent.StateChangedEventH\x00R\fstateChanged\x12D\n" +
	"\astarted\x18\x05 \x01(\v2(.baepo.core.v1.MachineEvent.StartedEventH\x00R\astarted\x12M\n" +
	"\n" +
	"terminated\x18\x06 \x01(\v2+.baepo.core.v1.MachineEvent.TerminatedEventH\x00R\n" +
	"terminated\x12j\n" +
	"\x15desired_state_changed\x18\a \x01(\v24.baepo.core.v1.MachineEvent.DesiredStateChangedEventH\x00R\x13desiredStateChanged\x12o\n" +
	"\x16reconciliation_started\x18\b \x01(\v26.baepo.core.v1.MachineEvent.ReconciliationStartedEventH\x00R\x15reconciliationStarted\x12u\n" +
	"\x18reconciliation_completed\x18\t \x01(\v28.baepo.core.v1.MachineEvent.ReconciliationCompletedEventH\x00R\x17reconciliationCompleted\x12e\n" +
	"\x11healthcheck_event\x18\n" +
	" \x01(\v26.baepo.core.v1.MachineEvent.ContainerStateChangedEventH\x00R\x10healthcheckEvent\x1aF\n" +
	"\x11StateChangedEvent\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.baepo.core.v1.MachineStateR\x05state\x1a]\n" +
	"\fStartedEvent\x12>\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\x1a\x9d\x01\n" +
	"\x0fTerminatedEvent\x12<\n" +
	"\x05cause\x18\x01 \x01(\x0e2&.baepo.core.v1.MachineTerminationCauseR\x05cause\x124\n" +
	"\x13termination_details\x18\x02 \x01(\tH\x00R\x12terminationDetails\x88\x01\x01B\x16\n" +
	"\x14_termination_details\x1ac\n" +
	"\x18DesiredStateChangedEvent\x12G\n" +
	"\rdesired_state\x18\x01 \x01(\x0e2\".baepo.core.v1.MachineDesiredStateR\fdesiredState\x1ae\n" +
	"\x1aReconciliationStartedEvent\x12G\n" +
	"\rdesired_state\x18\x01 \x01(\x0e2\".baepo.core.v1.MachineDesiredStateR\fdesiredState\x1a\x8c\x01\n" +
	"\x1cReconciliationCompletedEvent\x12G\n" +
	"\rdesired_state\x18\x01 \x01(\x0e2\".baepo.core.v1.MachineDesiredStateR\fdesiredState\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\x1a\x84\x04\n" +
	"\x1aContainerStateChangedEvent\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12:\n" +
	"\x05state\x18\x02 \x01(\x0e2$.baepo.core.v1.MachineContainerStateR\x05state\x12>\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartedAt\x88\x01\x01\x12<\n" +
	"\texited_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bexitedAt\x88\x01\x01\x12 \n" +
	"\texit_code\x18\x05 \x01(\x05H\x02R\bexitCode\x88\x01\x01\x12\"\n" +
	"\n" +
	"exit_error\x18\x06 \x01(\tH\x03R\texitError\x88\x01\x01\x12\x18\n" +
	"\ahealthy\x18\a \x01(\bR\ahealthy\x120\n" +
	"\x11healthcheck_error\x18\b \x01(\tH\x04R\x10healthcheckError\x88\x01\x01\x12#\n" +
	"\rrestart_count\x18\t \x01(\x05R\frestartCountB\r\n" +
	"\v_started_atB\f\n" +
	"\n" +
	"_exited_atB\f\n" +
	"\n" +
	"_exit_codeB\r\n" +
	"\v_exit_errorB\x14\n" +
	"\x12_healthcheck_errorB\a\n" +
	"\x05event*\xe5\x01\n" +
	"\fMachineState\x12\x18\n" +
	"\x14MachineState_Unknown\x10\x00\x12\x18\n" +
	"\x14MachineState_Pending\x10\x01\x12\x19\n" +
	"\x15MachineState_Starting\x10\x02\x12\x18\n" +
	"\x14MachineState_Running\x10\x03\x12\x19\n" +
	"\x15MachineState_Degraded\x10\x04\x12\x16\n" +
	"\x12MachineState_Error\x10\x05\x12\x1c\n" +
	"\x18MachineState_Terminating\x10\x06\x12\x1b\n" +
	"\x17MachineState_Terminated\x10\a*\x9c\x01\n" +
	"\x13MachineDesiredState\x12\x1f\n" +
	"\x1bMachineDesiredState_Unknown\x10\x00\x12\x1f\n" +
	"\x1bMachineDesiredState_Pending\x10\x01\x12\x1f\n" +
	"\x1bMachineDesiredState_Running\x10\x02\x12\"\n" +
	"\x1eMachineDesiredState_Terminated\x10\x03*\x99\x02\n" +
	"\x17MachineTerminationCause\x12#\n" +
	"\x1fMachineTerminationCause_Unknown\x10\x00\x12-\n" +
	")MachineTerminationCause_HealthcheckFailed\x10\x01\x12-\n" +
	")MachineTerminationCause_ManuallyRequested\x10\x02\x12)\n" +
	"%MachineTerminationCause_InternalError\x10\x03\x12+\n" +
	"'MachineTerminationCause_NoNodeAvailable\x10\x04\x12#\n" +
	"\x1fMachineTerminationCause_Expired\x10\x05*\x7f\n" +
	"\x15MachineContainerState\x12!\n" +
	"\x1dMachineContainerState_Unknown\x10\x00\x12!\n" +
	"\x1dMachineContainerState_Running\x10\x01\x12 \n" +
	"\x1cMachineContainerState_Exited\x10\x02B>Z<github.com/baepo-cloud/baepo-proto/go/baepo/core/v1;corev1pbb\x06proto3"

var (
	file_baepo_core_v1_machine_proto_rawDescOnce sync.Once
	file_baepo_core_v1_machine_proto_rawDescData []byte
)

func file_baepo_core_v1_machine_proto_rawDescGZIP() []byte {
	file_baepo_core_v1_machine_proto_rawDescOnce.Do(func() {
		file_baepo_core_v1_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baepo_core_v1_machine_proto_rawDesc), len(file_baepo_core_v1_machine_proto_rawDesc)))
	})
	return file_baepo_core_v1_machine_proto_rawDescData
}

var file_baepo_core_v1_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_baepo_core_v1_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_baepo_core_v1_machine_proto_goTypes = []any{
	(MachineState)(0),                       // 0: baepo.core.v1.MachineState
	(MachineDesiredState)(0),                // 1: baepo.core.v1.MachineDesiredState
	(MachineTerminationCause)(0),            // 2: baepo.core.v1.MachineTerminationCause
	(MachineContainerState)(0),              // 3: baepo.core.v1.MachineContainerState
	(MachineContainerRestartSpec_Policy)(0), // 4: baepo.core.v1.MachineContainerRestartSpec.Policy
	(*MachineSpec)(nil),                     // 5: baepo.core.v1.MachineSpec
	(*MachineContainerSpec)(nil),            // 6: baepo.core.v1.MachineContainerSpec
	(*MachineContainerRestartSpec)(nil),     // 7: baepo.core.v1.MachineContainerRestartSpec
	(*MachineContainerHealthcheckSpec)(nil), // 8: baepo.core.v1.MachineContainerHealthcheckSpec
	(*MachineEvent)(nil),                    // 9: baepo.core.v1.MachineEvent
	nil,                                     // 10: baepo.core.v1.MachineContainerSpec.EnvEntry
	(*MachineContainerHealthcheckSpec_HttpHealthcheckSpec)(nil), // 11: baepo.core.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec
	nil,                                               // 12: baepo.core.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.HeadersEntry
	(*MachineEvent_StateChangedEvent)(nil),            // 13: baepo.core.v1.MachineEvent.StateChangedEvent
	(*MachineEvent_StartedEvent)(nil),                 // 14: baepo.core.v1.MachineEvent.StartedEvent
	(*MachineEvent_TerminatedEvent)(nil),              // 15: baepo.core.v1.MachineEvent.TerminatedEvent
	(*MachineEvent_DesiredStateChangedEvent)(nil),     // 16: baepo.core.v1.MachineEvent.DesiredStateChangedEvent
	(*MachineEvent_ReconciliationStartedEvent)(nil),   // 17: baepo.core.v1.MachineEvent.ReconciliationStartedEvent
	(*MachineEvent_ReconciliationCompletedEvent)(nil), // 18: baepo.core.v1.MachineEvent.ReconciliationCompletedEvent
	(*MachineEvent_ContainerStateChangedEvent)(nil),   // 19: baepo.core.v1.MachineEvent.ContainerStateChangedEvent
	(*timestamppb.Timestamp)(nil),                     // 20: google.protobuf.Timestamp
}
var file_baepo_core_v1_machine_proto_depIdxs = []int32{
	6,  // 0: baepo.core.v1.MachineSpec.containers:type_name -> baepo.core.v1.MachineContainerSpec
	10, // 1: baepo.core.v1.MachineContainerSpec.env:type_name -> baepo.core.v1.MachineContainerSpec.EnvEntry
	8,  // 2: baepo.core.v1.MachineContainerSpec.healthcheck:type_name -> baepo.core.v1.MachineContainerHealthcheckSpec
	7,  // 3: baepo.core.v1.MachineContainerSpec.restart:type_name -> baepo.core.v1.MachineContainerRestartSpec
	4,  // 4: baepo.core.v1.MachineContainerRestartSpec.policy:type_name -> baepo.core.v1.MachineContainerRestartSpec.Policy
	11, // 5: baepo.core.v1.MachineContainerHealthcheckSpec.http:type_name -> baepo.core.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec
	20, // 6: baepo.core.v1.MachineEvent.timestamp:type_name -> google.protobuf.Timestamp
	13, // 7: baepo.core.v1.MachineEvent.state_changed:type_name -> baepo.core.v1.MachineEvent.StateChangedEvent
	14, // 8: baepo.core.v1.MachineEvent.started:type_name -> baepo.core.v1.MachineEvent.StartedEvent
	15, // 9: baepo.core.v1.MachineEvent.terminated:type_name -> baepo.core.v1.MachineEvent.TerminatedEvent
	16, // 10: baepo.core.v1.MachineEvent.desired_state_changed:type_name -> baepo.core.v1.MachineEvent.DesiredStateChangedEvent
	17, // 11: baepo.core.v1.MachineEvent.reconciliation_started:type_name -> baepo.core.v1.MachineEvent.ReconciliationStartedEvent
	18, // 12: baepo.core.v1.MachineEvent.reconciliation_completed:type_name -> baepo.core.v1.MachineEvent.ReconciliationCompletedEvent
	19, // 13: baepo.core.v1.MachineEvent.healthcheck_event:type_name -> baepo.core.v1.MachineEvent.ContainerStateChangedEvent
	12, // 14: baepo.core.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.headers:type_name -> baepo.core.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.HeadersEntry
	0,  // 15: baepo.core.v1.MachineEvent.StateChangedEvent.state:type_name -> baepo.core.v1.MachineState
	20, // 16: baepo.core.v1.MachineEvent.StartedEvent.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 17: baepo.core.v1.MachineEvent.TerminatedEvent.cause:type_name -> baepo.core.v1.MachineTerminationCause
	1,  // 18: baepo.core.v1.MachineEvent.DesiredStateChangedEvent.desired_state:type_name -> baepo.core.v1.MachineDesiredState
	1,  // 19: baepo.core.v1.MachineEvent.ReconciliationStartedEvent.desired_state:type_name -> baepo.core.v1.MachineDesiredState
	1,  // 20: baepo.core.v1.MachineEvent.ReconciliationCompletedEvent.desired_state:type_name -> baepo.core.v1.MachineDesiredState
	3,  // 21: baepo.core.v1.MachineEvent.ContainerStateChangedEvent.state:type_name -> baepo.core.v1.MachineContainerState
	20, // 22: baepo.core.v1.MachineEvent.ContainerStateChangedEvent.started_at:type_name -> google.protobuf.Timestamp
	20, // 23: baepo.core.v1.MachineEvent.ContainerStateChangedEvent.exited_at:type_name -> google.protobuf.Timestamp
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_baepo_core_v1_machine_proto_init() }
func file_baepo_core_v1_machine_proto_init() {
	if File_baepo_core_v1_machine_proto != nil {
		return
	}
	file_baepo_core_v1_machine_proto_msgTypes[0].OneofWrappers = []any{}
	file_baepo_core_v1_machine_proto_msgTypes[1].OneofWrappers = []any{}
	file_baepo_core_v1_machine_proto_msgTypes[3].OneofWrappers = []any{
		(*MachineContainerHealthcheckSpec_Http)(nil),
	}
	file_baepo_core_v1_machine_proto_msgTypes[4].OneofWrappers = []any{
		(*MachineEvent_StateChanged)(nil),
		(*MachineEvent_Started)(nil),
		(*MachineEvent_Terminated)(nil),
		(*MachineEvent_DesiredStateChanged)(nil),
		(*MachineEvent_ReconciliationStarted)(nil),
		(*MachineEvent_ReconciliationCompleted)(nil),
		(*MachineEvent_HealthcheckEvent)(nil),
	}
	file_baepo_core_v1_machine_proto_msgTypes[9].OneofWrappers = []any{}
	file_baepo_core_v1_machine_proto_msgTypes[10].OneofWrappers = []any{}
	file_baepo_core_v1_machine_proto_msgTypes[13].OneofWrappers = []any{}
	file_baepo_core_v1_machine_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_core_v1_machine_proto_rawDesc), len(file_baepo_core_v1_machine_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_baepo_core_v1_machine_proto_goTypes,
		DependencyIndexes: file_baepo_core_v1_machine_proto_depIdxs,
		EnumInfos:         file_baepo_core_v1_machine_proto_enumTypes,
		MessageInfos:      file_baepo_core_v1_machine_proto_msgTypes,
	}.Build()
	File_baepo_core_v1_machine_proto = out.File
	file_baepo_core_v1_machine_proto_goTypes = nil
	file_baepo_core_v1_machine_proto_depIdxs = nil
}
