// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/node/v1/init.proto

package nodev1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitGetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName *string                `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3,oneof" json:"container_name,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGetLogsRequest) Reset() {
	*x = InitGetLogsRequest{}
	mi := &file_baepo_node_v1_init_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGetLogsRequest) ProtoMessage() {}

func (x *InitGetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_init_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGetLogsRequest.ProtoReflect.Descriptor instead.
func (*InitGetLogsRequest) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_init_proto_rawDescGZIP(), []int{0}
}

func (x *InitGetLogsRequest) GetContainerName() string {
	if x != nil && x.ContainerName != nil {
		return *x.ContainerName
	}
	return ""
}

func (x *InitGetLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type InitGetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         bool                   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGetLogsResponse) Reset() {
	*x = InitGetLogsResponse{}
	mi := &file_baepo_node_v1_init_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGetLogsResponse) ProtoMessage() {}

func (x *InitGetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_init_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGetLogsResponse.ProtoReflect.Descriptor instead.
func (*InitGetLogsResponse) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_init_proto_rawDescGZIP(), []int{1}
}

func (x *InitGetLogsResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *InitGetLogsResponse) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *InitGetLogsResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InitGetLogsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_baepo_node_v1_init_proto protoreflect.FileDescriptor

const file_baepo_node_v1_init_proto_rawDesc = "" +
	"\n" +
	"\x18baepo/node/v1/init.proto\x12\rbaepo.node.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\x12InitGetLogsRequest\x12*\n" +
	"\x0econtainer_name\x18\x01 \x01(\tH\x00R\rcontainerName\x88\x01\x01\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06followB\x11\n" +
	"\x0f_container_name\"\xa6\x01\n" +
	"\x13InitGetLogsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x99\x01\n" +
	"\x04Init\x12R\n" +
	"\aGetLogs\x12!.baepo.node.v1.InitGetLogsRequest\x1a\".baepo.node.v1.InitGetLogsResponse0\x01\x12=\n" +
	"\vHealthcheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB>Z<github.com/baepo-cloud/baepo-proto/go/baepo/node/v1;nodev1pbb\x06proto3"

var (
	file_baepo_node_v1_init_proto_rawDescOnce sync.Once
	file_baepo_node_v1_init_proto_rawDescData []byte
)

func file_baepo_node_v1_init_proto_rawDescGZIP() []byte {
	file_baepo_node_v1_init_proto_rawDescOnce.Do(func() {
		file_baepo_node_v1_init_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baepo_node_v1_init_proto_rawDesc), len(file_baepo_node_v1_init_proto_rawDesc)))
	})
	return file_baepo_node_v1_init_proto_rawDescData
}

var file_baepo_node_v1_init_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_baepo_node_v1_init_proto_goTypes = []any{
	(*InitGetLogsRequest)(nil),    // 0: baepo.node.v1.InitGetLogsRequest
	(*InitGetLogsResponse)(nil),   // 1: baepo.node.v1.InitGetLogsResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_baepo_node_v1_init_proto_depIdxs = []int32{
	2, // 0: baepo.node.v1.InitGetLogsResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: baepo.node.v1.Init.GetLogs:input_type -> baepo.node.v1.InitGetLogsRequest
	3, // 2: baepo.node.v1.Init.Healthcheck:input_type -> google.protobuf.Empty
	1, // 3: baepo.node.v1.Init.GetLogs:output_type -> baepo.node.v1.InitGetLogsResponse
	3, // 4: baepo.node.v1.Init.Healthcheck:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_baepo_node_v1_init_proto_init() }
func file_baepo_node_v1_init_proto_init() {
	if File_baepo_node_v1_init_proto != nil {
		return
	}
	file_baepo_node_v1_init_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_node_v1_init_proto_rawDesc), len(file_baepo_node_v1_init_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baepo_node_v1_init_proto_goTypes,
		DependencyIndexes: file_baepo_node_v1_init_proto_depIdxs,
		MessageInfos:      file_baepo_node_v1_init_proto_msgTypes,
	}.Build()
	File_baepo_node_v1_init_proto = out.File
	file_baepo_node_v1_init_proto_goTypes = nil
	file_baepo_node_v1_init_proto_depIdxs = nil
}
