// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/node/v1/initd.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_baepo_node_v1_initd_proto protoreflect.FileDescriptor

const file_baepo_node_v1_initd_proto_rawDesc = "" +
	"\n" +
	"\x19baepo/node/v1/initd.proto\x12\rbaepo.node.v1\x1a\x1bgoogle/protobuf/empty.proto2F\n" +
	"\x05InitD\x12=\n" +
	"\vHealthcheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB5Z3github.com/baepo-cloud/baepo-proto/go/baepo/node/v1b\x06proto3"

var file_baepo_node_v1_initd_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
}
var file_baepo_node_v1_initd_proto_depIdxs = []int32{
	0, // 0: baepo.node.v1.InitD.Healthcheck:input_type -> google.protobuf.Empty
	0, // 1: baepo.node.v1.InitD.Healthcheck:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_baepo_node_v1_initd_proto_init() }
func file_baepo_node_v1_initd_proto_init() {
	if File_baepo_node_v1_initd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_node_v1_initd_proto_rawDesc), len(file_baepo_node_v1_initd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baepo_node_v1_initd_proto_goTypes,
		DependencyIndexes: file_baepo_node_v1_initd_proto_depIdxs,
	}.Build()
	File_baepo_node_v1_initd_proto = out.File
	file_baepo_node_v1_initd_proto_goTypes = nil
	file_baepo_node_v1_initd_proto_depIdxs = nil
}
