// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/node/v1/machine.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineState int32

const (
	MachineState_MachineState_Unknown     MachineState = 0
	MachineState_MachineState_Pending     MachineState = 1
	MachineState_MachineState_Starting    MachineState = 2
	MachineState_MachineState_Running     MachineState = 3
	MachineState_MachineState_Degraded    MachineState = 4
	MachineState_MachineState_Error       MachineState = 5
	MachineState_MachineState_Terminating MachineState = 6
	MachineState_MachineState_Terminated  MachineState = 7
)

// Enum value maps for MachineState.
var (
	MachineState_name = map[int32]string{
		0: "MachineState_Unknown",
		1: "MachineState_Pending",
		2: "MachineState_Starting",
		3: "MachineState_Running",
		4: "MachineState_Degraded",
		5: "MachineState_Error",
		6: "MachineState_Terminating",
		7: "MachineState_Terminated",
	}
	MachineState_value = map[string]int32{
		"MachineState_Unknown":     0,
		"MachineState_Pending":     1,
		"MachineState_Starting":    2,
		"MachineState_Running":     3,
		"MachineState_Degraded":    4,
		"MachineState_Error":       5,
		"MachineState_Terminating": 6,
		"MachineState_Terminated":  7,
	}
)

func (x MachineState) Enum() *MachineState {
	p := new(MachineState)
	*p = x
	return p
}

func (x MachineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineState) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_node_v1_machine_proto_enumTypes[0].Descriptor()
}

func (MachineState) Type() protoreflect.EnumType {
	return &file_baepo_node_v1_machine_proto_enumTypes[0]
}

func (x MachineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineState.Descriptor instead.
func (MachineState) EnumDescriptor() ([]byte, []int) {
	return file_baepo_node_v1_machine_proto_rawDescGZIP(), []int{0}
}

type MachineDesiredState int32

const (
	MachineDesiredState_MachineDesiredState_Unknown    MachineDesiredState = 0
	MachineDesiredState_MachineDesiredState_Pending    MachineDesiredState = 1
	MachineDesiredState_MachineDesiredState_Running    MachineDesiredState = 2
	MachineDesiredState_MachineDesiredState_Terminated MachineDesiredState = 3
)

// Enum value maps for MachineDesiredState.
var (
	MachineDesiredState_name = map[int32]string{
		0: "MachineDesiredState_Unknown",
		1: "MachineDesiredState_Pending",
		2: "MachineDesiredState_Running",
		3: "MachineDesiredState_Terminated",
	}
	MachineDesiredState_value = map[string]int32{
		"MachineDesiredState_Unknown":    0,
		"MachineDesiredState_Pending":    1,
		"MachineDesiredState_Running":    2,
		"MachineDesiredState_Terminated": 3,
	}
)

func (x MachineDesiredState) Enum() *MachineDesiredState {
	p := new(MachineDesiredState)
	*p = x
	return p
}

func (x MachineDesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineDesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_node_v1_machine_proto_enumTypes[1].Descriptor()
}

func (MachineDesiredState) Type() protoreflect.EnumType {
	return &file_baepo_node_v1_machine_proto_enumTypes[1]
}

func (x MachineDesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineDesiredState.Descriptor instead.
func (MachineDesiredState) EnumDescriptor() ([]byte, []int) {
	return file_baepo_node_v1_machine_proto_rawDescGZIP(), []int{1}
}

type MachineTerminationCause int32

const (
	MachineTerminationCause_MachineTerminationCause_Unknown           MachineTerminationCause = 0
	MachineTerminationCause_MachineTerminationCause_HealthcheckFailed MachineTerminationCause = 1
	MachineTerminationCause_MachineTerminationCause_ManuallyRequested MachineTerminationCause = 2
	MachineTerminationCause_MachineTerminationCause_InternalError     MachineTerminationCause = 3
	MachineTerminationCause_MachineTerminationCause_NoNodeAvailable   MachineTerminationCause = 4
	MachineTerminationCause_MachineTerminationCause_Expired           MachineTerminationCause = 5
)

// Enum value maps for MachineTerminationCause.
var (
	MachineTerminationCause_name = map[int32]string{
		0: "MachineTerminationCause_Unknown",
		1: "MachineTerminationCause_HealthcheckFailed",
		2: "MachineTerminationCause_ManuallyRequested",
		3: "MachineTerminationCause_InternalError",
		4: "MachineTerminationCause_NoNodeAvailable",
		5: "MachineTerminationCause_Expired",
	}
	MachineTerminationCause_value = map[string]int32{
		"MachineTerminationCause_Unknown":           0,
		"MachineTerminationCause_HealthcheckFailed": 1,
		"MachineTerminationCause_ManuallyRequested": 2,
		"MachineTerminationCause_InternalError":     3,
		"MachineTerminationCause_NoNodeAvailable":   4,
		"MachineTerminationCause_Expired":           5,
	}
)

func (x MachineTerminationCause) Enum() *MachineTerminationCause {
	p := new(MachineTerminationCause)
	*p = x
	return p
}

func (x MachineTerminationCause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineTerminationCause) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_node_v1_machine_proto_enumTypes[2].Descriptor()
}

func (MachineTerminationCause) Type() protoreflect.EnumType {
	return &file_baepo_node_v1_machine_proto_enumTypes[2]
}

func (x MachineTerminationCause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineTerminationCause.Descriptor instead.
func (MachineTerminationCause) EnumDescriptor() ([]byte, []int) {
	return file_baepo_node_v1_machine_proto_rawDescGZIP(), []int{2}
}

type MachineSpec struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Cpus          uint32                  `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryMb      uint64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Containers    []*MachineContainerSpec `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	Timeout       *uint64                 `protobuf:"varint,4,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_baepo_node_v1_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetCpus() uint32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *MachineSpec) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *MachineSpec) GetContainers() []*MachineContainerSpec {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *MachineSpec) GetTimeout() uint64 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

type MachineContainerSpec struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Image         string                           `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Env           map[string]string                `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command       []string                         `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Healthcheck   *MachineContainerHealthcheckSpec `protobuf:"bytes,4,opt,name=healthcheck,proto3" json:"healthcheck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineContainerSpec) Reset() {
	*x = MachineContainerSpec{}
	mi := &file_baepo_node_v1_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContainerSpec) ProtoMessage() {}

func (x *MachineContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContainerSpec.ProtoReflect.Descriptor instead.
func (*MachineContainerSpec) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_machine_proto_rawDescGZIP(), []int{1}
}

func (x *MachineContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MachineContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *MachineContainerSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *MachineContainerSpec) GetHealthcheck() *MachineContainerHealthcheckSpec {
	if x != nil {
		return x.Healthcheck
	}
	return nil
}

type MachineContainerHealthcheckSpec struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InitialDelaySeconds int32                  `protobuf:"varint,1,opt,name=initial_delay_seconds,json=initialDelaySeconds,proto3" json:"initial_delay_seconds,omitempty"`
	PeriodSeconds       int32                  `protobuf:"varint,2,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*MachineContainerHealthcheckSpec_Http
	Type          isMachineContainerHealthcheckSpec_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineContainerHealthcheckSpec) Reset() {
	*x = MachineContainerHealthcheckSpec{}
	mi := &file_baepo_node_v1_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContainerHealthcheckSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContainerHealthcheckSpec) ProtoMessage() {}

func (x *MachineContainerHealthcheckSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContainerHealthcheckSpec.ProtoReflect.Descriptor instead.
func (*MachineContainerHealthcheckSpec) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_machine_proto_rawDescGZIP(), []int{2}
}

func (x *MachineContainerHealthcheckSpec) GetInitialDelaySeconds() int32 {
	if x != nil {
		return x.InitialDelaySeconds
	}
	return 0
}

func (x *MachineContainerHealthcheckSpec) GetPeriodSeconds() int32 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

func (x *MachineContainerHealthcheckSpec) GetType() isMachineContainerHealthcheckSpec_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MachineContainerHealthcheckSpec) GetHttp() *MachineContainerHealthcheckSpec_HttpHealthcheckSpec {
	if x != nil {
		if x, ok := x.Type.(*MachineContainerHealthcheckSpec_Http); ok {
			return x.Http
		}
	}
	return nil
}

type isMachineContainerHealthcheckSpec_Type interface {
	isMachineContainerHealthcheckSpec_Type()
}

type MachineContainerHealthcheckSpec_Http struct {
	Http *MachineContainerHealthcheckSpec_HttpHealthcheckSpec `protobuf:"bytes,3,opt,name=http,proto3,oneof"`
}

func (*MachineContainerHealthcheckSpec_Http) isMachineContainerHealthcheckSpec_Type() {}

type Machine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	State         MachineState           `protobuf:"varint,2,opt,name=state,proto3,enum=baepo.node.v1.MachineState" json:"state,omitempty"`
	DesiredState  MachineDesiredState    `protobuf:"varint,3,opt,name=desired_state,json=desiredState,proto3,enum=baepo.node.v1.MachineDesiredState" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_baepo_node_v1_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_machine_proto_rawDescGZIP(), []int{3}
}

func (x *Machine) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Machine) GetState() MachineState {
	if x != nil {
		return x.State
	}
	return MachineState_MachineState_Unknown
}

func (x *Machine) GetDesiredState() MachineDesiredState {
	if x != nil {
		return x.DesiredState
	}
	return MachineDesiredState_MachineDesiredState_Unknown
}

type MachineContainerHealthcheckSpec_HttpHealthcheckSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) Reset() {
	*x = MachineContainerHealthcheckSpec_HttpHealthcheckSpec{}
	mi := &file_baepo_node_v1_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContainerHealthcheckSpec_HttpHealthcheckSpec) ProtoMessage() {}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContainerHealthcheckSpec_HttpHealthcheckSpec.ProtoReflect.Descriptor instead.
func (*MachineContainerHealthcheckSpec_HttpHealthcheckSpec) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_machine_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MachineContainerHealthcheckSpec_HttpHealthcheckSpec) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_baepo_node_v1_machine_proto protoreflect.FileDescriptor

const file_baepo_node_v1_machine_proto_rawDesc = "" +
	"\n" +
	"\x1bbaepo/node/v1/machine.proto\x12\rbaepo.node.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x01\n" +
	"\vMachineSpec\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\rR\x04cpus\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x04R\bmemoryMb\x12C\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2#.baepo.node.v1.MachineContainerSpecR\n" +
	"containers\x12\x1d\n" +
	"\atimeout\x18\x04 \x01(\x04H\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\"\x90\x02\n" +
	"\x14MachineContainerSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12>\n" +
	"\x03env\x18\x02 \x03(\v2,.baepo.node.v1.MachineContainerSpec.EnvEntryR\x03env\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12P\n" +
	"\vhealthcheck\x18\x04 \x01(\v2..baepo.node.v1.MachineContainerHealthcheckSpecR\vhealthcheck\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x03\n" +
	"\x1fMachineContainerHealthcheckSpec\x122\n" +
	"\x15initial_delay_seconds\x18\x01 \x01(\x05R\x13initialDelaySeconds\x12%\n" +
	"\x0eperiod_seconds\x18\x02 \x01(\x05R\rperiodSeconds\x12X\n" +
	"\x04http\x18\x03 \x01(\v2B.baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpecH\x00R\x04http\x1a\xfc\x01\n" +
	"\x13HttpHealthcheckSpec\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12i\n" +
	"\aheaders\x18\x04 \x03(\v2O.baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04type\"\xa4\x01\n" +
	"\aMachine\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x121\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1b.baepo.node.v1.MachineStateR\x05state\x12G\n" +
	"\rdesired_state\x18\x03 \x01(\x0e2\".baepo.node.v1.MachineDesiredStateR\fdesiredState*\xe5\x01\n" +
	"\fMachineState\x12\x18\n" +
	"\x14MachineState_Unknown\x10\x00\x12\x18\n" +
	"\x14MachineState_Pending\x10\x01\x12\x19\n" +
	"\x15MachineState_Starting\x10\x02\x12\x18\n" +
	"\x14MachineState_Running\x10\x03\x12\x19\n" +
	"\x15MachineState_Degraded\x10\x04\x12\x16\n" +
	"\x12MachineState_Error\x10\x05\x12\x1c\n" +
	"\x18MachineState_Terminating\x10\x06\x12\x1b\n" +
	"\x17MachineState_Terminated\x10\a*\x9c\x01\n" +
	"\x13MachineDesiredState\x12\x1f\n" +
	"\x1bMachineDesiredState_Unknown\x10\x00\x12\x1f\n" +
	"\x1bMachineDesiredState_Pending\x10\x01\x12\x1f\n" +
	"\x1bMachineDesiredState_Running\x10\x02\x12\"\n" +
	"\x1eMachineDesiredState_Terminated\x10\x03*\x99\x02\n" +
	"\x17MachineTerminationCause\x12#\n" +
	"\x1fMachineTerminationCause_Unknown\x10\x00\x12-\n" +
	")MachineTerminationCause_HealthcheckFailed\x10\x01\x12-\n" +
	")MachineTerminationCause_ManuallyRequested\x10\x02\x12)\n" +
	"%MachineTerminationCause_InternalError\x10\x03\x12+\n" +
	"'MachineTerminationCause_NoNodeAvailable\x10\x04\x12#\n" +
	"\x1fMachineTerminationCause_Expired\x10\x05B5Z3github.com/baepo-cloud/baepo-proto/go/baepo/node/v1b\x06proto3"

var (
	file_baepo_node_v1_machine_proto_rawDescOnce sync.Once
	file_baepo_node_v1_machine_proto_rawDescData []byte
)

func file_baepo_node_v1_machine_proto_rawDescGZIP() []byte {
	file_baepo_node_v1_machine_proto_rawDescOnce.Do(func() {
		file_baepo_node_v1_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baepo_node_v1_machine_proto_rawDesc), len(file_baepo_node_v1_machine_proto_rawDesc)))
	})
	return file_baepo_node_v1_machine_proto_rawDescData
}

var file_baepo_node_v1_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_baepo_node_v1_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_baepo_node_v1_machine_proto_goTypes = []any{
	(MachineState)(0),                       // 0: baepo.node.v1.MachineState
	(MachineDesiredState)(0),                // 1: baepo.node.v1.MachineDesiredState
	(MachineTerminationCause)(0),            // 2: baepo.node.v1.MachineTerminationCause
	(*MachineSpec)(nil),                     // 3: baepo.node.v1.MachineSpec
	(*MachineContainerSpec)(nil),            // 4: baepo.node.v1.MachineContainerSpec
	(*MachineContainerHealthcheckSpec)(nil), // 5: baepo.node.v1.MachineContainerHealthcheckSpec
	(*Machine)(nil),                         // 6: baepo.node.v1.Machine
	nil,                                     // 7: baepo.node.v1.MachineContainerSpec.EnvEntry
	(*MachineContainerHealthcheckSpec_HttpHealthcheckSpec)(nil), // 8: baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec
	nil, // 9: baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.HeadersEntry
}
var file_baepo_node_v1_machine_proto_depIdxs = []int32{
	4, // 0: baepo.node.v1.MachineSpec.containers:type_name -> baepo.node.v1.MachineContainerSpec
	7, // 1: baepo.node.v1.MachineContainerSpec.env:type_name -> baepo.node.v1.MachineContainerSpec.EnvEntry
	5, // 2: baepo.node.v1.MachineContainerSpec.healthcheck:type_name -> baepo.node.v1.MachineContainerHealthcheckSpec
	8, // 3: baepo.node.v1.MachineContainerHealthcheckSpec.http:type_name -> baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec
	0, // 4: baepo.node.v1.Machine.state:type_name -> baepo.node.v1.MachineState
	1, // 5: baepo.node.v1.Machine.desired_state:type_name -> baepo.node.v1.MachineDesiredState
	9, // 6: baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.headers:type_name -> baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.HeadersEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_baepo_node_v1_machine_proto_init() }
func file_baepo_node_v1_machine_proto_init() {
	if File_baepo_node_v1_machine_proto != nil {
		return
	}
	file_baepo_node_v1_machine_proto_msgTypes[0].OneofWrappers = []any{}
	file_baepo_node_v1_machine_proto_msgTypes[2].OneofWrappers = []any{
		(*MachineContainerHealthcheckSpec_Http)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_node_v1_machine_proto_rawDesc), len(file_baepo_node_v1_machine_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_baepo_node_v1_machine_proto_goTypes,
		DependencyIndexes: file_baepo_node_v1_machine_proto_depIdxs,
		EnumInfos:         file_baepo_node_v1_machine_proto_enumTypes,
		MessageInfos:      file_baepo_node_v1_machine_proto_msgTypes,
	}.Build()
	File_baepo_node_v1_machine_proto = out.File
	file_baepo_node_v1_machine_proto_goTypes = nil
	file_baepo_node_v1_machine_proto_depIdxs = nil
}
