// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/node/v1/node.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeMachineState int32

const (
	NodeMachineState_NodeMachineState_Unknown  NodeMachineState = 0
	NodeMachineState_NodeMachineState_Running  NodeMachineState = 1
	NodeMachineState_NodeMachineState_Degraded NodeMachineState = 2
	NodeMachineState_NodeMachineState_Failed   NodeMachineState = 3
)

// Enum value maps for NodeMachineState.
var (
	NodeMachineState_name = map[int32]string{
		0: "NodeMachineState_Unknown",
		1: "NodeMachineState_Running",
		2: "NodeMachineState_Degraded",
		3: "NodeMachineState_Failed",
	}
	NodeMachineState_value = map[string]int32{
		"NodeMachineState_Unknown":  0,
		"NodeMachineState_Running":  1,
		"NodeMachineState_Degraded": 2,
		"NodeMachineState_Failed":   3,
	}
)

func (x NodeMachineState) Enum() *NodeMachineState {
	p := new(NodeMachineState)
	*p = x
	return p
}

func (x NodeMachineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeMachineState) Descriptor() protoreflect.EnumDescriptor {
	return file_baepo_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (NodeMachineState) Type() protoreflect.EnumType {
	return &file_baepo_node_v1_node_proto_enumTypes[0]
}

func (x NodeMachineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeMachineState.Descriptor instead.
func (NodeMachineState) EnumDescriptor() ([]byte, []int) {
	return file_baepo_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type NodeStartMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	VCpus         uint32                 `protobuf:"varint,2,opt,name=v_cpus,json=vCpus,proto3" json:"v_cpus,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStartMachineRequest) Reset() {
	*x = NodeStartMachineRequest{}
	mi := &file_baepo_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStartMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStartMachineRequest) ProtoMessage() {}

func (x *NodeStartMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStartMachineRequest.ProtoReflect.Descriptor instead.
func (*NodeStartMachineRequest) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStartMachineRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *NodeStartMachineRequest) GetVCpus() uint32 {
	if x != nil {
		return x.VCpus
	}
	return 0
}

func (x *NodeStartMachineRequest) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *NodeStartMachineRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type NodeStartMachineReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *NodeMachine           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStartMachineReply) Reset() {
	*x = NodeStartMachineReply{}
	mi := &file_baepo_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStartMachineReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStartMachineReply) ProtoMessage() {}

func (x *NodeStartMachineReply) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStartMachineReply.ProtoReflect.Descriptor instead.
func (*NodeStartMachineReply) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStartMachineReply) GetMachine() *NodeMachine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type NodeMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	State         NodeMachineState       `protobuf:"varint,2,opt,name=state,proto3,enum=baepo.node.v1.NodeMachineState" json:"state,omitempty"`
	Pid           int64                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	TapInterface  string                 `protobuf:"bytes,4,opt,name=tap_interface,json=tapInterface,proto3" json:"tap_interface,omitempty"`
	MacAddress    string                 `protobuf:"bytes,5,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMachine) Reset() {
	*x = NodeMachine{}
	mi := &file_baepo_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMachine) ProtoMessage() {}

func (x *NodeMachine) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMachine.ProtoReflect.Descriptor instead.
func (*NodeMachine) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMachine) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *NodeMachine) GetState() NodeMachineState {
	if x != nil {
		return x.State
	}
	return NodeMachineState_NodeMachineState_Unknown
}

func (x *NodeMachine) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NodeMachine) GetTapInterface() string {
	if x != nil {
		return x.TapInterface
	}
	return ""
}

func (x *NodeMachine) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NodeMachine) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type NodeStopMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStopMachineRequest) Reset() {
	*x = NodeStopMachineRequest{}
	mi := &file_baepo_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStopMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStopMachineRequest) ProtoMessage() {}

func (x *NodeStopMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStopMachineRequest.ProtoReflect.Descriptor instead.
func (*NodeStopMachineRequest) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStopMachineRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type NodeHealthcheckMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHealthcheckMachineRequest) Reset() {
	*x = NodeHealthcheckMachineRequest{}
	mi := &file_baepo_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthcheckMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthcheckMachineRequest) ProtoMessage() {}

func (x *NodeHealthcheckMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthcheckMachineRequest.ProtoReflect.Descriptor instead.
func (*NodeHealthcheckMachineRequest) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *NodeHealthcheckMachineRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type NodeHealthcheckMachineReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *NodeMachine           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHealthcheckMachineReply) Reset() {
	*x = NodeHealthcheckMachineReply{}
	mi := &file_baepo_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthcheckMachineReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthcheckMachineReply) ProtoMessage() {}

func (x *NodeHealthcheckMachineReply) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthcheckMachineReply.ProtoReflect.Descriptor instead.
func (*NodeHealthcheckMachineReply) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *NodeHealthcheckMachineReply) GetMachine() *NodeMachine {
	if x != nil {
		return x.Machine
	}
	return nil
}

var File_baepo_node_v1_node_proto protoreflect.FileDescriptor

const file_baepo_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x18baepo/node/v1/node.proto\x12\rbaepo.node.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xe7\x01\n" +
	"\x17NodeStartMachineRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x15\n" +
	"\x06v_cpus\x18\x02 \x01(\rR\x05vCpus\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x04R\bmemoryMb\x12A\n" +
	"\x03env\x18\x04 \x03(\v2/.baepo.node.v1.NodeStartMachineRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x15NodeStartMachineReply\x124\n" +
	"\amachine\x18\x01 \x01(\v2\x1a.baepo.node.v1.NodeMachineR\amachine\"\xda\x01\n" +
	"\vNodeMachine\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.baepo.node.v1.NodeMachineStateR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\x12#\n" +
	"\rtap_interface\x18\x04 \x01(\tR\ftapInterface\x12\x1f\n" +
	"\vmac_address\x18\x05 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\"7\n" +
	"\x16NodeStopMachineRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\">\n" +
	"\x1dNodeHealthcheckMachineRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\"S\n" +
	"\x1bNodeHealthcheckMachineReply\x124\n" +
	"\amachine\x18\x01 \x01(\v2\x1a.baepo.node.v1.NodeMachineR\amachine*\x8a\x01\n" +
	"\x10NodeMachineState\x12\x1c\n" +
	"\x18NodeMachineState_Unknown\x10\x00\x12\x1c\n" +
	"\x18NodeMachineState_Running\x10\x01\x12\x1d\n" +
	"\x19NodeMachineState_Degraded\x10\x02\x12\x1b\n" +
	"\x17NodeMachineState_Failed\x10\x032\xa9\x02\n" +
	"\vNodeService\x12\\\n" +
	"\fStartMachine\x12&.baepo.node.v1.NodeStartMachineRequest\x1a$.baepo.node.v1.NodeStartMachineReply\x12L\n" +
	"\vStopMachine\x12%.baepo.node.v1.NodeStopMachineRequest\x1a\x16.google.protobuf.Empty\x12n\n" +
	"\x12HealthcheckMachine\x12,.baepo.node.v1.NodeHealthcheckMachineRequest\x1a*.baepo.node.v1.NodeHealthcheckMachineReplyB5Z3github.com/baepo-cloud/baepo-proto/go/baepo/node/v1b\x06proto3"

var (
	file_baepo_node_v1_node_proto_rawDescOnce sync.Once
	file_baepo_node_v1_node_proto_rawDescData []byte
)

func file_baepo_node_v1_node_proto_rawDescGZIP() []byte {
	file_baepo_node_v1_node_proto_rawDescOnce.Do(func() {
		file_baepo_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baepo_node_v1_node_proto_rawDesc), len(file_baepo_node_v1_node_proto_rawDesc)))
	})
	return file_baepo_node_v1_node_proto_rawDescData
}

var file_baepo_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_baepo_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_baepo_node_v1_node_proto_goTypes = []any{
	(NodeMachineState)(0),                 // 0: baepo.node.v1.NodeMachineState
	(*NodeStartMachineRequest)(nil),       // 1: baepo.node.v1.NodeStartMachineRequest
	(*NodeStartMachineReply)(nil),         // 2: baepo.node.v1.NodeStartMachineReply
	(*NodeMachine)(nil),                   // 3: baepo.node.v1.NodeMachine
	(*NodeStopMachineRequest)(nil),        // 4: baepo.node.v1.NodeStopMachineRequest
	(*NodeHealthcheckMachineRequest)(nil), // 5: baepo.node.v1.NodeHealthcheckMachineRequest
	(*NodeHealthcheckMachineReply)(nil),   // 6: baepo.node.v1.NodeHealthcheckMachineReply
	nil,                                   // 7: baepo.node.v1.NodeStartMachineRequest.EnvEntry
	(*emptypb.Empty)(nil),                 // 8: google.protobuf.Empty
}
var file_baepo_node_v1_node_proto_depIdxs = []int32{
	7, // 0: baepo.node.v1.NodeStartMachineRequest.env:type_name -> baepo.node.v1.NodeStartMachineRequest.EnvEntry
	3, // 1: baepo.node.v1.NodeStartMachineReply.machine:type_name -> baepo.node.v1.NodeMachine
	0, // 2: baepo.node.v1.NodeMachine.state:type_name -> baepo.node.v1.NodeMachineState
	3, // 3: baepo.node.v1.NodeHealthcheckMachineReply.machine:type_name -> baepo.node.v1.NodeMachine
	1, // 4: baepo.node.v1.NodeService.StartMachine:input_type -> baepo.node.v1.NodeStartMachineRequest
	4, // 5: baepo.node.v1.NodeService.StopMachine:input_type -> baepo.node.v1.NodeStopMachineRequest
	5, // 6: baepo.node.v1.NodeService.HealthcheckMachine:input_type -> baepo.node.v1.NodeHealthcheckMachineRequest
	2, // 7: baepo.node.v1.NodeService.StartMachine:output_type -> baepo.node.v1.NodeStartMachineReply
	8, // 8: baepo.node.v1.NodeService.StopMachine:output_type -> google.protobuf.Empty
	6, // 9: baepo.node.v1.NodeService.HealthcheckMachine:output_type -> baepo.node.v1.NodeHealthcheckMachineReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_baepo_node_v1_node_proto_init() }
func file_baepo_node_v1_node_proto_init() {
	if File_baepo_node_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_node_v1_node_proto_rawDesc), len(file_baepo_node_v1_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baepo_node_v1_node_proto_goTypes,
		DependencyIndexes: file_baepo_node_v1_node_proto_depIdxs,
		EnumInfos:         file_baepo_node_v1_node_proto_enumTypes,
		MessageInfos:      file_baepo_node_v1_node_proto_msgTypes,
	}.Build()
	File_baepo_node_v1_node_proto = out.File
	file_baepo_node_v1_node_proto_goTypes = nil
	file_baepo_node_v1_node_proto_depIdxs = nil
}
