// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/node/v1/runtime_init.proto

package nodev1pb

import (
	v1 "github.com/baepo-cloud/baepo-proto/go/baepo/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeInitWriteLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Error         bool                   `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInitWriteLogRequest) Reset() {
	*x = RuntimeInitWriteLogRequest{}
	mi := &file_baepo_node_v1_runtime_init_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInitWriteLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInitWriteLogRequest) ProtoMessage() {}

func (x *RuntimeInitWriteLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_runtime_init_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInitWriteLogRequest.ProtoReflect.Descriptor instead.
func (*RuntimeInitWriteLogRequest) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_runtime_init_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeInitWriteLogRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RuntimeInitWriteLogRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RuntimeInitWriteLogRequest) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *RuntimeInitWriteLogRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *RuntimeInitWriteLogRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RuntimeInitUpdateContainerStateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerId      string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	State            v1.ContainerState      `protobuf:"varint,2,opt,name=state,proto3,enum=baepo.core.v1.ContainerState" json:"state,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	ExitedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=exited_at,json=exitedAt,proto3,oneof" json:"exited_at,omitempty"`
	ExitCode         *int32                 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	ExitError        *string                `protobuf:"bytes,6,opt,name=exit_error,json=exitError,proto3,oneof" json:"exit_error,omitempty"`
	Healthy          bool                   `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`
	HealthcheckError *string                `protobuf:"bytes,8,opt,name=healthcheck_error,json=healthcheckError,proto3,oneof" json:"healthcheck_error,omitempty"`
	RestartCount     int32                  `protobuf:"varint,9,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuntimeInitUpdateContainerStateRequest) Reset() {
	*x = RuntimeInitUpdateContainerStateRequest{}
	mi := &file_baepo_node_v1_runtime_init_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInitUpdateContainerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInitUpdateContainerStateRequest) ProtoMessage() {}

func (x *RuntimeInitUpdateContainerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_node_v1_runtime_init_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInitUpdateContainerStateRequest.ProtoReflect.Descriptor instead.
func (*RuntimeInitUpdateContainerStateRequest) Descriptor() ([]byte, []int) {
	return file_baepo_node_v1_runtime_init_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeInitUpdateContainerStateRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RuntimeInitUpdateContainerStateRequest) GetState() v1.ContainerState {
	if x != nil {
		return x.State
	}
	return v1.ContainerState(0)
}

func (x *RuntimeInitUpdateContainerStateRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RuntimeInitUpdateContainerStateRequest) GetExitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitedAt
	}
	return nil
}

func (x *RuntimeInitUpdateContainerStateRequest) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *RuntimeInitUpdateContainerStateRequest) GetExitError() string {
	if x != nil && x.ExitError != nil {
		return *x.ExitError
	}
	return ""
}

func (x *RuntimeInitUpdateContainerStateRequest) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *RuntimeInitUpdateContainerStateRequest) GetHealthcheckError() string {
	if x != nil && x.HealthcheckError != nil {
		return *x.HealthcheckError
	}
	return ""
}

func (x *RuntimeInitUpdateContainerStateRequest) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

var File_baepo_node_v1_runtime_init_proto protoreflect.FileDescriptor

const file_baepo_node_v1_runtime_init_proto_rawDesc = "" +
	"\n" +
	" baepo/node/v1/runtime_init.proto\x12\rbaepo.node.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dbaepo/core/v1/container.proto\"\xd0\x01\n" +
	"\x1aRuntimeInitWriteLogRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05error\x18\x03 \x01(\bR\x05error\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x85\x04\n" +
	"&RuntimeInitUpdateContainerStateRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x123\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1d.baepo.core.v1.ContainerStateR\x05state\x12>\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartedAt\x88\x01\x01\x12<\n" +
	"\texited_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bexitedAt\x88\x01\x01\x12 \n" +
	"\texit_code\x18\x05 \x01(\x05H\x02R\bexitCode\x88\x01\x01\x12\"\n" +
	"\n" +
	"exit_error\x18\x06 \x01(\tH\x03R\texitError\x88\x01\x01\x12\x18\n" +
	"\ahealthy\x18\a \x01(\bR\ahealthy\x120\n" +
	"\x11healthcheck_error\x18\b \x01(\tH\x04R\x10healthcheckError\x88\x01\x01\x12#\n" +
	"\rrestart_count\x18\t \x01(\x05R\frestartCountB\r\n" +
	"\v_started_atB\f\n" +
	"\n" +
	"_exited_atB\f\n" +
	"\n" +
	"_exit_codeB\r\n" +
	"\v_exit_errorB\x14\n" +
	"\x12_healthcheck_error2\xc7\x01\n" +
	"\vRuntimeInit\x12Q\n" +
	"\bWriteLog\x12).baepo.node.v1.RuntimeInitWriteLogRequest\x1a\x16.google.protobuf.Empty(\x010\x01\x12e\n" +
	"\x14UpdateContainerState\x125.baepo.node.v1.RuntimeInitUpdateContainerStateRequest\x1a\x16.google.protobuf.EmptyB>Z<github.com/baepo-cloud/baepo-proto/go/baepo/node/v1;nodev1pbb\x06proto3"

var (
	file_baepo_node_v1_runtime_init_proto_rawDescOnce sync.Once
	file_baepo_node_v1_runtime_init_proto_rawDescData []byte
)

func file_baepo_node_v1_runtime_init_proto_rawDescGZIP() []byte {
	file_baepo_node_v1_runtime_init_proto_rawDescOnce.Do(func() {
		file_baepo_node_v1_runtime_init_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baepo_node_v1_runtime_init_proto_rawDesc), len(file_baepo_node_v1_runtime_init_proto_rawDesc)))
	})
	return file_baepo_node_v1_runtime_init_proto_rawDescData
}

var file_baepo_node_v1_runtime_init_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_baepo_node_v1_runtime_init_proto_goTypes = []any{
	(*RuntimeInitWriteLogRequest)(nil),             // 0: baepo.node.v1.RuntimeInitWriteLogRequest
	(*RuntimeInitUpdateContainerStateRequest)(nil), // 1: baepo.node.v1.RuntimeInitUpdateContainerStateRequest
	(*timestamppb.Timestamp)(nil),                  // 2: google.protobuf.Timestamp
	(v1.ContainerState)(0),                         // 3: baepo.core.v1.ContainerState
	(*emptypb.Empty)(nil),                          // 4: google.protobuf.Empty
}
var file_baepo_node_v1_runtime_init_proto_depIdxs = []int32{
	2, // 0: baepo.node.v1.RuntimeInitWriteLogRequest.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: baepo.node.v1.RuntimeInitUpdateContainerStateRequest.state:type_name -> baepo.core.v1.ContainerState
	2, // 2: baepo.node.v1.RuntimeInitUpdateContainerStateRequest.started_at:type_name -> google.protobuf.Timestamp
	2, // 3: baepo.node.v1.RuntimeInitUpdateContainerStateRequest.exited_at:type_name -> google.protobuf.Timestamp
	0, // 4: baepo.node.v1.RuntimeInit.WriteLog:input_type -> baepo.node.v1.RuntimeInitWriteLogRequest
	1, // 5: baepo.node.v1.RuntimeInit.UpdateContainerState:input_type -> baepo.node.v1.RuntimeInitUpdateContainerStateRequest
	4, // 6: baepo.node.v1.RuntimeInit.WriteLog:output_type -> google.protobuf.Empty
	4, // 7: baepo.node.v1.RuntimeInit.UpdateContainerState:output_type -> google.protobuf.Empty
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_baepo_node_v1_runtime_init_proto_init() }
func file_baepo_node_v1_runtime_init_proto_init() {
	if File_baepo_node_v1_runtime_init_proto != nil {
		return
	}
	file_baepo_node_v1_runtime_init_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_node_v1_runtime_init_proto_rawDesc), len(file_baepo_node_v1_runtime_init_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baepo_node_v1_runtime_init_proto_goTypes,
		DependencyIndexes: file_baepo_node_v1_runtime_init_proto_depIdxs,
		MessageInfos:      file_baepo_node_v1_runtime_init_proto_msgTypes,
	}.Build()
	File_baepo_node_v1_runtime_init_proto = out.File
	file_baepo_node_v1_runtime_init_proto_goTypes = nil
	file_baepo_node_v1_runtime_init_proto_depIdxs = nil
}
