// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=js"
// @generated from file baepo/initd/v1/initd.proto (package baepo.initd.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/initd/v1/initd.proto.
 */
export const file_baepo_initd_v1_initd = /*@__PURE__*/
  fileDesc("ChpiYWVwby9pbml0ZC92MS9pbml0ZC5wcm90bxIOYmFlcG8uaW5pdGQudjEyRgoFSW5pdEQSPQoLSGVhbHRoY2hlY2sSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHlCQFo+Z2l0aHViLmNvbS9iYWVwby1jbG91ZC9iYWVwby1wcm90by9nby9iYWVwby9pbml0ZC92MTtpbml0ZHYxcGJiBnByb3RvMw", [file_google_protobuf_empty]);

/**
 * @generated from service baepo.initd.v1.InitD
 */
export const InitD = /*@__PURE__*/
  serviceDesc(file_baepo_initd_v1_initd, 0);

