// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=js"
// @generated from file baepo/initd/v1/initd.proto (package baepo.initd.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/initd/v1/initd.proto.
 */
export declare const file_baepo_initd_v1_initd: GenFile;

/**
 * @generated from service baepo.initd.v1.InitD
 */
export declare const InitD: GenService<{
  /**
   * @generated from rpc baepo.initd.v1.InitD.Healthcheck
   */
  healthcheck: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof EmptySchema;
  },
}>;

