// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=js"
// @generated from file baepo/node/v1/init.proto (package baepo.node.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_baepo_core_v1_container } from "../../core/v1/container_pb.js";

/**
 * Describes the file baepo/node/v1/init.proto.
 */
export const file_baepo_node_v1_init = /*@__PURE__*/
  fileDesc("ChhiYWVwby9ub2RlL3YxL2luaXQucHJvdG8SDWJhZXBvLm5vZGUudjEiFAoSSW5pdEdldExvZ3NSZXF1ZXN0InoKE0luaXRHZXRMb2dzUmVzcG9uc2USFAoMY29udGFpbmVyX2lkGAEgASgJEg0KBWVycm9yGAIgASgIEg8KB2NvbnRlbnQYAyABKAwSLQoJdGltZXN0YW1wGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCKeBQoSSW5pdEV2ZW50c1Jlc3BvbnNlEhAKCGV2ZW50X2lkGAEgASgJEi0KCXRpbWVzdGFtcBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASXwoXY29udGFpbmVyX3N0YXRlX2NoYW5nZWQYAyABKAsyPC5iYWVwby5ub2RlLnYxLkluaXRFdmVudHNSZXNwb25zZS5Db250YWluZXJTdGF0ZUNoYW5nZWRFdmVudEgAEjsKBHBpbmcYBCABKAsyKy5iYWVwby5ub2RlLnYxLkluaXRFdmVudHNSZXNwb25zZS5QaW5nRXZlbnRIABqSAwoaQ29udGFpbmVyU3RhdGVDaGFuZ2VkRXZlbnQSFAoMY29udGFpbmVyX2lkGAEgASgJEiwKBXN0YXRlGAIgASgOMh0uYmFlcG8uY29yZS52MS5Db250YWluZXJTdGF0ZRIzCgpzdGFydGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBEjIKCWV4aXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAYgBARIWCglleGl0X2NvZGUYBSABKAVIAogBARIXCgpleGl0X2Vycm9yGAYgASgJSAOIAQESDwoHaGVhbHRoeRgHIAEoCBIeChFoZWFsdGhjaGVja19lcnJvchgIIAEoCUgEiAEBEhUKDXJlc3RhcnRfY291bnQYCSABKAVCDQoLX3N0YXJ0ZWRfYXRCDAoKX2V4aXRlZF9hdEIMCgpfZXhpdF9jb2RlQg0KC19leGl0X2Vycm9yQhQKEl9oZWFsdGhjaGVja19lcnJvchoLCglQaW5nRXZlbnRCBwoFZXZlbnQyoQEKBEluaXQSUgoHR2V0TG9ncxIhLmJhZXBvLm5vZGUudjEuSW5pdEdldExvZ3NSZXF1ZXN0GiIuYmFlcG8ubm9kZS52MS5Jbml0R2V0TG9nc1Jlc3BvbnNlMAESRQoGRXZlbnRzEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiEuYmFlcG8ubm9kZS52MS5Jbml0RXZlbnRzUmVzcG9uc2UwAUI+WjxnaXRodWIuY29tL2JhZXBvLWNsb3VkL2JhZXBvLXByb3RvL2dvL2JhZXBvL25vZGUvdjE7bm9kZXYxcGJiBnByb3RvMw", [file_google_protobuf_empty, file_google_protobuf_timestamp, file_baepo_core_v1_container]);

/**
 * Describes the message baepo.node.v1.InitGetLogsRequest.
 * Use `create(InitGetLogsRequestSchema)` to create a new message.
 */
export const InitGetLogsRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_node_v1_init, 0);

/**
 * Describes the message baepo.node.v1.InitGetLogsResponse.
 * Use `create(InitGetLogsResponseSchema)` to create a new message.
 */
export const InitGetLogsResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_node_v1_init, 1);

/**
 * Describes the message baepo.node.v1.InitEventsResponse.
 * Use `create(InitEventsResponseSchema)` to create a new message.
 */
export const InitEventsResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_node_v1_init, 2);

/**
 * Describes the message baepo.node.v1.InitEventsResponse.ContainerStateChangedEvent.
 * Use `create(InitEventsResponse_ContainerStateChangedEventSchema)` to create a new message.
 */
export const InitEventsResponse_ContainerStateChangedEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_node_v1_init, 2, 0);

/**
 * Describes the message baepo.node.v1.InitEventsResponse.PingEvent.
 * Use `create(InitEventsResponse_PingEventSchema)` to create a new message.
 */
export const InitEventsResponse_PingEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_node_v1_init, 2, 1);

/**
 * @generated from service baepo.node.v1.Init
 */
export const Init = /*@__PURE__*/
  serviceDesc(file_baepo_node_v1_init, 0);

