// @generated by protoc-gen-es v2.2.5
// @generated from file baepo/node/v1/machine.proto (package baepo.node.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file baepo/node/v1/machine.proto.
 */
export declare const file_baepo_node_v1_machine: GenFile;

/**
 * @generated from message baepo.node.v1.MachineSpec
 */
export declare type MachineSpec = Message<"baepo.node.v1.MachineSpec"> & {
  /**
   * @generated from field: uint32 cpus = 1;
   */
  cpus: number;

  /**
   * @generated from field: uint64 memory_mb = 2;
   */
  memoryMb: bigint;

  /**
   * @generated from field: repeated baepo.node.v1.MachineContainerSpec containers = 3;
   */
  containers: MachineContainerSpec[];

  /**
   * @generated from field: optional uint64 timeout = 4;
   */
  timeout?: bigint;
};

/**
 * Describes the message baepo.node.v1.MachineSpec.
 * Use `create(MachineSpecSchema)` to create a new message.
 */
export declare const MachineSpecSchema: GenMessage<MachineSpec>;

/**
 * @generated from message baepo.node.v1.MachineContainerSpec
 */
export declare type MachineContainerSpec = Message<"baepo.node.v1.MachineContainerSpec"> & {
  /**
   * @generated from field: string image = 1;
   */
  image: string;

  /**
   * @generated from field: map<string, string> env = 2;
   */
  env: { [key: string]: string };

  /**
   * @generated from field: repeated string command = 3;
   */
  command: string[];

  /**
   * @generated from field: baepo.node.v1.MachineContainerHealthcheckSpec healthcheck = 4;
   */
  healthcheck?: MachineContainerHealthcheckSpec;
};

/**
 * Describes the message baepo.node.v1.MachineContainerSpec.
 * Use `create(MachineContainerSpecSchema)` to create a new message.
 */
export declare const MachineContainerSpecSchema: GenMessage<MachineContainerSpec>;

/**
 * @generated from message baepo.node.v1.MachineContainerHealthcheckSpec
 */
export declare type MachineContainerHealthcheckSpec = Message<"baepo.node.v1.MachineContainerHealthcheckSpec"> & {
  /**
   * @generated from field: int32 initial_delay_seconds = 1;
   */
  initialDelaySeconds: number;

  /**
   * @generated from field: int32 period_seconds = 2;
   */
  periodSeconds: number;

  /**
   * @generated from oneof baepo.node.v1.MachineContainerHealthcheckSpec.type
   */
  type: {
    /**
     * @generated from field: baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec http = 3;
     */
    value: MachineContainerHealthcheckSpec_HttpHealthcheckSpec;
    case: "http";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message baepo.node.v1.MachineContainerHealthcheckSpec.
 * Use `create(MachineContainerHealthcheckSpecSchema)` to create a new message.
 */
export declare const MachineContainerHealthcheckSpecSchema: GenMessage<MachineContainerHealthcheckSpec>;

/**
 * @generated from message baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec
 */
export declare type MachineContainerHealthcheckSpec_HttpHealthcheckSpec = Message<"baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec"> & {
  /**
   * @generated from field: string method = 1;
   */
  method: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: int32 port = 3;
   */
  port: number;

  /**
   * @generated from field: map<string, string> headers = 4;
   */
  headers: { [key: string]: string };
};

/**
 * Describes the message baepo.node.v1.MachineContainerHealthcheckSpec.HttpHealthcheckSpec.
 * Use `create(MachineContainerHealthcheckSpec_HttpHealthcheckSpecSchema)` to create a new message.
 */
export declare const MachineContainerHealthcheckSpec_HttpHealthcheckSpecSchema: GenMessage<MachineContainerHealthcheckSpec_HttpHealthcheckSpec>;

/**
 * @generated from message baepo.node.v1.Machine
 */
export declare type Machine = Message<"baepo.node.v1.Machine"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;

  /**
   * @generated from field: baepo.node.v1.MachineState state = 2;
   */
  state: MachineState;

  /**
   * @generated from field: baepo.node.v1.MachineDesiredState desired_state = 3;
   */
  desiredState: MachineDesiredState;
};

/**
 * Describes the message baepo.node.v1.Machine.
 * Use `create(MachineSchema)` to create a new message.
 */
export declare const MachineSchema: GenMessage<Machine>;

/**
 * @generated from enum baepo.node.v1.MachineState
 */
export enum MachineState {
  /**
   * @generated from enum value: MachineState_Unknown = 0;
   */
  MachineState_Unknown = 0,

  /**
   * @generated from enum value: MachineState_Pending = 1;
   */
  MachineState_Pending = 1,

  /**
   * @generated from enum value: MachineState_Starting = 2;
   */
  MachineState_Starting = 2,

  /**
   * @generated from enum value: MachineState_Running = 3;
   */
  MachineState_Running = 3,

  /**
   * @generated from enum value: MachineState_Degraded = 4;
   */
  MachineState_Degraded = 4,

  /**
   * @generated from enum value: MachineState_Error = 5;
   */
  MachineState_Error = 5,

  /**
   * @generated from enum value: MachineState_Terminating = 6;
   */
  MachineState_Terminating = 6,

  /**
   * @generated from enum value: MachineState_Terminated = 7;
   */
  MachineState_Terminated = 7,
}

/**
 * Describes the enum baepo.node.v1.MachineState.
 */
export declare const MachineStateSchema: GenEnum<MachineState>;

/**
 * @generated from enum baepo.node.v1.MachineDesiredState
 */
export enum MachineDesiredState {
  /**
   * @generated from enum value: MachineDesiredState_Unknown = 0;
   */
  MachineDesiredState_Unknown = 0,

  /**
   * @generated from enum value: MachineDesiredState_Pending = 1;
   */
  MachineDesiredState_Pending = 1,

  /**
   * @generated from enum value: MachineDesiredState_Running = 2;
   */
  MachineDesiredState_Running = 2,

  /**
   * @generated from enum value: MachineDesiredState_Terminated = 3;
   */
  MachineDesiredState_Terminated = 3,
}

/**
 * Describes the enum baepo.node.v1.MachineDesiredState.
 */
export declare const MachineDesiredStateSchema: GenEnum<MachineDesiredState>;

