// @generated by protoc-gen-es v2.2.5
// @generated from file baepo/node/v1/node.proto (package baepo.node.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Machine, MachineDesiredState, MachineSpec } from "./machine_pb";

/**
 * Describes the file baepo/node/v1/node.proto.
 */
export declare const file_baepo_node_v1_node: GenFile;

/**
 * @generated from message baepo.node.v1.NodeListMachinesRequest
 */
export declare type NodeListMachinesRequest = Message<"baepo.node.v1.NodeListMachinesRequest"> & {
};

/**
 * Describes the message baepo.node.v1.NodeListMachinesRequest.
 * Use `create(NodeListMachinesRequestSchema)` to create a new message.
 */
export declare const NodeListMachinesRequestSchema: GenMessage<NodeListMachinesRequest>;

/**
 * @generated from message baepo.node.v1.NodeListMachinesResponse
 */
export declare type NodeListMachinesResponse = Message<"baepo.node.v1.NodeListMachinesResponse"> & {
  /**
   * @generated from field: repeated baepo.node.v1.Machine machines = 1;
   */
  machines: Machine[];
};

/**
 * Describes the message baepo.node.v1.NodeListMachinesResponse.
 * Use `create(NodeListMachinesResponseSchema)` to create a new message.
 */
export declare const NodeListMachinesResponseSchema: GenMessage<NodeListMachinesResponse>;

/**
 * @generated from message baepo.node.v1.NodeGetMachineRequest
 */
export declare type NodeGetMachineRequest = Message<"baepo.node.v1.NodeGetMachineRequest"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;
};

/**
 * Describes the message baepo.node.v1.NodeGetMachineRequest.
 * Use `create(NodeGetMachineRequestSchema)` to create a new message.
 */
export declare const NodeGetMachineRequestSchema: GenMessage<NodeGetMachineRequest>;

/**
 * @generated from message baepo.node.v1.NodeGetMachineResponse
 */
export declare type NodeGetMachineResponse = Message<"baepo.node.v1.NodeGetMachineResponse"> & {
  /**
   * @generated from field: baepo.node.v1.Machine machine = 1;
   */
  machine?: Machine;
};

/**
 * Describes the message baepo.node.v1.NodeGetMachineResponse.
 * Use `create(NodeGetMachineResponseSchema)` to create a new message.
 */
export declare const NodeGetMachineResponseSchema: GenMessage<NodeGetMachineResponse>;

/**
 * @generated from message baepo.node.v1.NodeCreateMachineRequest
 */
export declare type NodeCreateMachineRequest = Message<"baepo.node.v1.NodeCreateMachineRequest"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;

  /**
   * @generated from field: baepo.node.v1.MachineSpec spec = 2;
   */
  spec?: MachineSpec;

  /**
   * @generated from field: baepo.node.v1.MachineDesiredState desired_state = 3;
   */
  desiredState: MachineDesiredState;
};

/**
 * Describes the message baepo.node.v1.NodeCreateMachineRequest.
 * Use `create(NodeCreateMachineRequestSchema)` to create a new message.
 */
export declare const NodeCreateMachineRequestSchema: GenMessage<NodeCreateMachineRequest>;

/**
 * @generated from message baepo.node.v1.NodeCreateMachineResponse
 */
export declare type NodeCreateMachineResponse = Message<"baepo.node.v1.NodeCreateMachineResponse"> & {
  /**
   * @generated from field: baepo.node.v1.Machine machine = 1;
   */
  machine?: Machine;
};

/**
 * Describes the message baepo.node.v1.NodeCreateMachineResponse.
 * Use `create(NodeCreateMachineResponseSchema)` to create a new message.
 */
export declare const NodeCreateMachineResponseSchema: GenMessage<NodeCreateMachineResponse>;

/**
 * @generated from message baepo.node.v1.NodeUpdateMachineDesiredStateRequest
 */
export declare type NodeUpdateMachineDesiredStateRequest = Message<"baepo.node.v1.NodeUpdateMachineDesiredStateRequest"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;

  /**
   * @generated from field: baepo.node.v1.MachineDesiredState desired_state = 2;
   */
  desiredState: MachineDesiredState;
};

/**
 * Describes the message baepo.node.v1.NodeUpdateMachineDesiredStateRequest.
 * Use `create(NodeUpdateMachineDesiredStateRequestSchema)` to create a new message.
 */
export declare const NodeUpdateMachineDesiredStateRequestSchema: GenMessage<NodeUpdateMachineDesiredStateRequest>;

/**
 * @generated from message baepo.node.v1.NodeUpdateMachineDesiredStateResponse
 */
export declare type NodeUpdateMachineDesiredStateResponse = Message<"baepo.node.v1.NodeUpdateMachineDesiredStateResponse"> & {
  /**
   * @generated from field: baepo.node.v1.Machine machine = 1;
   */
  machine?: Machine;
};

/**
 * Describes the message baepo.node.v1.NodeUpdateMachineDesiredStateResponse.
 * Use `create(NodeUpdateMachineDesiredStateResponseSchema)` to create a new message.
 */
export declare const NodeUpdateMachineDesiredStateResponseSchema: GenMessage<NodeUpdateMachineDesiredStateResponse>;

/**
 * @generated from service baepo.node.v1.NodeService
 */
export declare const NodeService: GenService<{
  /**
   * @generated from rpc baepo.node.v1.NodeService.ListMachines
   */
  listMachines: {
    methodKind: "unary";
    input: typeof NodeListMachinesRequestSchema;
    output: typeof NodeListMachinesResponseSchema;
  },
  /**
   * @generated from rpc baepo.node.v1.NodeService.GetMachine
   */
  getMachine: {
    methodKind: "unary";
    input: typeof NodeGetMachineRequestSchema;
    output: typeof NodeGetMachineResponseSchema;
  },
  /**
   * @generated from rpc baepo.node.v1.NodeService.CreateMachine
   */
  createMachine: {
    methodKind: "unary";
    input: typeof NodeCreateMachineRequestSchema;
    output: typeof NodeCreateMachineResponseSchema;
  },
  /**
   * @generated from rpc baepo.node.v1.NodeService.UpdateMachineDesiredState
   */
  updateMachineDesiredState: {
    methodKind: "unary";
    input: typeof NodeUpdateMachineDesiredStateRequestSchema;
    output: typeof NodeUpdateMachineDesiredStateResponseSchema;
  },
}>;

