// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=js"
// @generated from file baepo/node/v1/runtime_init.proto (package baepo.node.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_baepo_core_v1_container } from "../../core/v1/container_pb.js";

/**
 * Describes the file baepo/node/v1/runtime_init.proto.
 */
export const file_baepo_node_v1_runtime_init = /*@__PURE__*/
  fileDesc("CiBiYWVwby9ub2RlL3YxL3J1bnRpbWVfaW5pdC5wcm90bxINYmFlcG8ubm9kZS52MSKZAQoaUnVudGltZUluaXRXcml0ZUxvZ1JlcXVlc3QSFAoMY29udGFpbmVyX2lkGAEgASgJEhYKDmNvbnRhaW5lcl9uYW1lGAIgASgJEg0KBWVycm9yGAMgASgIEg8KB2NvbnRlbnQYBCABKAwSLQoJdGltZXN0YW1wGAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCKeAwomUnVudGltZUluaXRVcGRhdGVDb250YWluZXJTdGF0ZVJlcXVlc3QSFAoMY29udGFpbmVyX2lkGAEgASgJEiwKBXN0YXRlGAIgASgOMh0uYmFlcG8uY29yZS52MS5Db250YWluZXJTdGF0ZRIzCgpzdGFydGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBEjIKCWV4aXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAYgBARIWCglleGl0X2NvZGUYBSABKAVIAogBARIXCgpleGl0X2Vycm9yGAYgASgJSAOIAQESDwoHaGVhbHRoeRgHIAEoCBIeChFoZWFsdGhjaGVja19lcnJvchgIIAEoCUgEiAEBEhUKDXJlc3RhcnRfY291bnQYCSABKAVCDQoLX3N0YXJ0ZWRfYXRCDAoKX2V4aXRlZF9hdEIMCgpfZXhpdF9jb2RlQg0KC19leGl0X2Vycm9yQhQKEl9oZWFsdGhjaGVja19lcnJvcjLHAQoLUnVudGltZUluaXQSUQoIV3JpdGVMb2cSKS5iYWVwby5ub2RlLnYxLlJ1bnRpbWVJbml0V3JpdGVMb2dSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5KAEwARJlChRVcGRhdGVDb250YWluZXJTdGF0ZRI1LmJhZXBvLm5vZGUudjEuUnVudGltZUluaXRVcGRhdGVDb250YWluZXJTdGF0ZVJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHlCPlo8Z2l0aHViLmNvbS9iYWVwby1jbG91ZC9iYWVwby1wcm90by9nby9iYWVwby9ub2RlL3YxO25vZGV2MXBiYgZwcm90bzM", [file_google_protobuf_empty, file_google_protobuf_timestamp, file_baepo_core_v1_container]);

/**
 * Describes the message baepo.node.v1.RuntimeInitWriteLogRequest.
 * Use `create(RuntimeInitWriteLogRequestSchema)` to create a new message.
 */
export const RuntimeInitWriteLogRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_node_v1_runtime_init, 0);

/**
 * Describes the message baepo.node.v1.RuntimeInitUpdateContainerStateRequest.
 * Use `create(RuntimeInitUpdateContainerStateRequestSchema)` to create a new message.
 */
export const RuntimeInitUpdateContainerStateRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_node_v1_runtime_init, 1);

/**
 * @generated from service baepo.node.v1.RuntimeInit
 */
export const RuntimeInit = /*@__PURE__*/
  serviceDesc(file_baepo_node_v1_runtime_init, 0);

