// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=js"
// @generated from file baepo/api/v1/auth.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/auth.proto.
 */
export const file_baepo_api_v1_auth = /*@__PURE__*/
  fileDesc("ChdiYWVwby9hcGkvdjEvYXV0aC5wcm90bxIMYmFlcG8uYXBpLnYxIl0KE0F1dGhSZWdpc3RlclJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSEgoKZmlyc3RfbmFtZRgDIAEoCRIRCglsYXN0X25hbWUYBCABKAkiOwoUQXV0aFJlZ2lzdGVyUmVzcG9uc2USDwoHdXNlcl9pZBgBIAEoCRISCgpzZWNyZXRfa2V5GAIgASgJIjMKEEF1dGhMb2dpblJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiOAoRQXV0aExvZ2luUmVzcG9uc2USDwoHdXNlcl9pZBgBIAEoCRISCgpzZWNyZXRfa2V5GAIgASgJMqoBCgtBdXRoU2VydmljZRJRCghSZWdpc3RlchIhLmJhZXBvLmFwaS52MS5BdXRoUmVnaXN0ZXJSZXF1ZXN0GiIuYmFlcG8uYXBpLnYxLkF1dGhSZWdpc3RlclJlc3BvbnNlEkgKBUxvZ2luEh4uYmFlcG8uYXBpLnYxLkF1dGhMb2dpblJlcXVlc3QaHy5iYWVwby5hcGkudjEuQXV0aExvZ2luUmVzcG9uc2VCPFo6Z2l0aHViLmNvbS9iYWVwby1jbG91ZC9iYWVwby1wcm90by9nby9iYWVwby9hcGkvdjE7YXBpdjFwYmIGcHJvdG8z", [file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * Describes the message baepo.api.v1.AuthRegisterRequest.
 * Use `create(AuthRegisterRequestSchema)` to create a new message.
 */
export const AuthRegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_auth, 0);

/**
 * Describes the message baepo.api.v1.AuthRegisterResponse.
 * Use `create(AuthRegisterResponseSchema)` to create a new message.
 */
export const AuthRegisterResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_auth, 1);

/**
 * Describes the message baepo.api.v1.AuthLoginRequest.
 * Use `create(AuthLoginRequestSchema)` to create a new message.
 */
export const AuthLoginRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_auth, 2);

/**
 * Describes the message baepo.api.v1.AuthLoginResponse.
 * Use `create(AuthLoginResponseSchema)` to create a new message.
 */
export const AuthLoginResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_auth, 3);

/**
 * @generated from service baepo.api.v1.AuthService
 */
export const AuthService = /*@__PURE__*/
  serviceDesc(file_baepo_api_v1_auth, 0);

