// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=js"
// @generated from file baepo/api/v1/auth.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file baepo/api/v1/auth.proto.
 */
export declare const file_baepo_api_v1_auth: GenFile;

/**
 * @generated from message baepo.api.v1.AuthRegisterRequest
 */
export declare type AuthRegisterRequest = Message<"baepo.api.v1.AuthRegisterRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string first_name = 3;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 4;
   */
  lastName: string;
};

/**
 * Describes the message baepo.api.v1.AuthRegisterRequest.
 * Use `create(AuthRegisterRequestSchema)` to create a new message.
 */
export declare const AuthRegisterRequestSchema: GenMessage<AuthRegisterRequest>;

/**
 * @generated from message baepo.api.v1.AuthRegisterResponse
 */
export declare type AuthRegisterResponse = Message<"baepo.api.v1.AuthRegisterResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string secret_key = 2;
   */
  secretKey: string;
};

/**
 * Describes the message baepo.api.v1.AuthRegisterResponse.
 * Use `create(AuthRegisterResponseSchema)` to create a new message.
 */
export declare const AuthRegisterResponseSchema: GenMessage<AuthRegisterResponse>;

/**
 * @generated from message baepo.api.v1.AuthLoginRequest
 */
export declare type AuthLoginRequest = Message<"baepo.api.v1.AuthLoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message baepo.api.v1.AuthLoginRequest.
 * Use `create(AuthLoginRequestSchema)` to create a new message.
 */
export declare const AuthLoginRequestSchema: GenMessage<AuthLoginRequest>;

/**
 * @generated from message baepo.api.v1.AuthLoginResponse
 */
export declare type AuthLoginResponse = Message<"baepo.api.v1.AuthLoginResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string secret_key = 2;
   */
  secretKey: string;
};

/**
 * Describes the message baepo.api.v1.AuthLoginResponse.
 * Use `create(AuthLoginResponseSchema)` to create a new message.
 */
export declare const AuthLoginResponseSchema: GenMessage<AuthLoginResponse>;

/**
 * @generated from service baepo.api.v1.AuthService
 */
export declare const AuthService: GenService<{
  /**
   * @generated from rpc baepo.api.v1.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof AuthRegisterRequestSchema;
    output: typeof AuthRegisterResponseSchema;
  },
  /**
   * @generated from rpc baepo.api.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof AuthLoginRequestSchema;
    output: typeof AuthLoginResponseSchema;
  },
}>;

