// @generated by protoc-gen-es v2.2.5
// @generated from file baepo/api/v1/cluster.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/cluster.proto.
 */
export const file_baepo_api_v1_cluster = /*@__PURE__*/
  fileDesc("ChpiYWVwby9hcGkvdjEvY2x1c3Rlci5wcm90bxIMYmFlcG8uYXBpLnYxIrkCCgdDbHVzdGVyEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSHAoPYm9vdHN0cmFwX3Rva2VuGAMgASgJSACIAQESEgoKY2FuX21hbmFnZRgEIAEoCBIuCgpjcmVhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIzCgpkZWxldGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgBiAEBEhkKDHdvcmtzcGFjZV9pZBgIIAEoCUgCiAEBQhIKEF9ib290c3RyYXBfdG9rZW5CDQoLX2RlbGV0ZWRfYXRCDwoNX3dvcmtzcGFjZV9pZCIqChJDbHVzdGVyTGlzdFJlcXVlc3QSFAoMd29ya3NwYWNlX2lkGAEgASgJIj4KE0NsdXN0ZXJMaXN0UmVzcG9uc2USJwoIY2x1c3RlcnMYASADKAsyFS5iYWVwby5hcGkudjEuQ2x1c3RlciIkChRDbHVzdGVyQ3JlYXRlUmVxdWVzdBIMCgRuYW1lGAEgASgJIj8KFUNsdXN0ZXJDcmVhdGVSZXNwb25zZRImCgdjbHVzdGVyGAEgASgLMhUuYmFlcG8uYXBpLnYxLkNsdXN0ZXIiKgoUQ2x1c3RlckRlbGV0ZVJlcXVlc3QSEgoKY2x1c3Rlcl9pZBgBIAEoCSI/ChVDbHVzdGVyRGVsZXRlUmVzcG9uc2USJgoHY2x1c3RlchgBIAEoCzIVLmJhZXBvLmFwaS52MS5DbHVzdGVyMoMCCg5DbHVzdGVyU2VydmljZRJLCgRMaXN0EiAuYmFlcG8uYXBpLnYxLkNsdXN0ZXJMaXN0UmVxdWVzdBohLmJhZXBvLmFwaS52MS5DbHVzdGVyTGlzdFJlc3BvbnNlElEKBkNyZWF0ZRIiLmJhZXBvLmFwaS52MS5DbHVzdGVyQ3JlYXRlUmVxdWVzdBojLmJhZXBvLmFwaS52MS5DbHVzdGVyQ3JlYXRlUmVzcG9uc2USUQoGRGVsZXRlEiIuYmFlcG8uYXBpLnYxLkNsdXN0ZXJEZWxldGVSZXF1ZXN0GiMuYmFlcG8uYXBpLnYxLkNsdXN0ZXJEZWxldGVSZXNwb25zZUI0WjJnaXRodWIuY29tL2JhZXBvLWNsb3VkL2JhZXBvLXByb3RvL2dvL2JhZXBvL2FwaS92MWIGcHJvdG8z", [file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * Describes the message baepo.api.v1.Cluster.
 * Use `create(ClusterSchema)` to create a new message.
 */
export const ClusterSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_cluster, 0);

/**
 * Describes the message baepo.api.v1.ClusterListRequest.
 * Use `create(ClusterListRequestSchema)` to create a new message.
 */
export const ClusterListRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_cluster, 1);

/**
 * Describes the message baepo.api.v1.ClusterListResponse.
 * Use `create(ClusterListResponseSchema)` to create a new message.
 */
export const ClusterListResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_cluster, 2);

/**
 * Describes the message baepo.api.v1.ClusterCreateRequest.
 * Use `create(ClusterCreateRequestSchema)` to create a new message.
 */
export const ClusterCreateRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_cluster, 3);

/**
 * Describes the message baepo.api.v1.ClusterCreateResponse.
 * Use `create(ClusterCreateResponseSchema)` to create a new message.
 */
export const ClusterCreateResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_cluster, 4);

/**
 * Describes the message baepo.api.v1.ClusterDeleteRequest.
 * Use `create(ClusterDeleteRequestSchema)` to create a new message.
 */
export const ClusterDeleteRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_cluster, 5);

/**
 * Describes the message baepo.api.v1.ClusterDeleteResponse.
 * Use `create(ClusterDeleteResponseSchema)` to create a new message.
 */
export const ClusterDeleteResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_cluster, 6);

/**
 * @generated from service baepo.api.v1.ClusterService
 */
export const ClusterService = /*@__PURE__*/
  serviceDesc(file_baepo_api_v1_cluster, 0);

