// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=js"
// @generated from file baepo/api/v1/machine.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { MachineDesiredState, MachineSpec, MachineState, MachineTerminationCause } from "../../core/v1/machine_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/machine.proto.
 */
export declare const file_baepo_api_v1_machine: GenFile;

/**
 * @generated from message baepo.api.v1.Machine
 */
export declare type Machine = Message<"baepo.api.v1.Machine"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: baepo.core.v1.MachineState state = 3;
   */
  state: MachineState;

  /**
   * @generated from field: optional string node_id = 4;
   */
  nodeId?: string;

  /**
   * @generated from field: baepo.core.v1.MachineSpec spec = 5;
   */
  spec?: MachineSpec;

  /**
   * @generated from field: baepo.core.v1.MachineDesiredState desired_state = 6;
   */
  desiredState: MachineDesiredState;

  /**
   * @generated from field: optional google.protobuf.Timestamp started_at = 7;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp expires_at = 8;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp terminated_at = 9;
   */
  terminatedAt?: Timestamp;

  /**
   * @generated from field: optional baepo.core.v1.MachineTerminationCause termination_cause = 10;
   */
  terminationCause?: MachineTerminationCause;

  /**
   * @generated from field: optional string termination_details = 11;
   */
  terminationDetails?: string;

  /**
   * @generated from field: map<string, string> metadata = 12;
   */
  metadata: { [key: string]: string };

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 13;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 14;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: string workspace_id = 15;
   */
  workspaceId: string;
};

/**
 * Describes the message baepo.api.v1.Machine.
 * Use `create(MachineSchema)` to create a new message.
 */
export declare const MachineSchema: GenMessage<Machine>;

/**
 * @generated from message baepo.api.v1.MachineListRequest
 */
export declare type MachineListRequest = Message<"baepo.api.v1.MachineListRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;
};

/**
 * Describes the message baepo.api.v1.MachineListRequest.
 * Use `create(MachineListRequestSchema)` to create a new message.
 */
export declare const MachineListRequestSchema: GenMessage<MachineListRequest>;

/**
 * @generated from message baepo.api.v1.MachineListResponse
 */
export declare type MachineListResponse = Message<"baepo.api.v1.MachineListResponse"> & {
  /**
   * @generated from field: repeated baepo.api.v1.Machine machines = 1;
   */
  machines: Machine[];
};

/**
 * Describes the message baepo.api.v1.MachineListResponse.
 * Use `create(MachineListResponseSchema)` to create a new message.
 */
export declare const MachineListResponseSchema: GenMessage<MachineListResponse>;

/**
 * @generated from message baepo.api.v1.MachineFindByIdRequest
 */
export declare type MachineFindByIdRequest = Message<"baepo.api.v1.MachineFindByIdRequest"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;
};

/**
 * Describes the message baepo.api.v1.MachineFindByIdRequest.
 * Use `create(MachineFindByIdRequestSchema)` to create a new message.
 */
export declare const MachineFindByIdRequestSchema: GenMessage<MachineFindByIdRequest>;

/**
 * @generated from message baepo.api.v1.MachineFindByIdResponse
 */
export declare type MachineFindByIdResponse = Message<"baepo.api.v1.MachineFindByIdResponse"> & {
  /**
   * @generated from field: baepo.api.v1.Machine machine = 1;
   */
  machine?: Machine;
};

/**
 * Describes the message baepo.api.v1.MachineFindByIdResponse.
 * Use `create(MachineFindByIdResponseSchema)` to create a new message.
 */
export declare const MachineFindByIdResponseSchema: GenMessage<MachineFindByIdResponse>;

/**
 * @generated from message baepo.api.v1.MachineCreateRequest
 */
export declare type MachineCreateRequest = Message<"baepo.api.v1.MachineCreateRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: baepo.core.v1.MachineSpec spec = 3;
   */
  spec?: MachineSpec;

  /**
   * @generated from field: map<string, string> metadata = 4;
   */
  metadata: { [key: string]: string };

  /**
   * @generated from field: bool start = 5;
   */
  start: boolean;

  /**
   * @generated from oneof baepo.api.v1.MachineCreateRequest.placement
   */
  placement: {
    /**
     * @generated from field: string node_id = 6;
     */
    value: string;
    case: "nodeId";
  } | {
    /**
     * @generated from field: string cluster_id = 7;
     */
    value: string;
    case: "clusterId";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message baepo.api.v1.MachineCreateRequest.
 * Use `create(MachineCreateRequestSchema)` to create a new message.
 */
export declare const MachineCreateRequestSchema: GenMessage<MachineCreateRequest>;

/**
 * @generated from message baepo.api.v1.MachineCreateResponse
 */
export declare type MachineCreateResponse = Message<"baepo.api.v1.MachineCreateResponse"> & {
  /**
   * @generated from field: baepo.api.v1.Machine machine = 1;
   */
  machine?: Machine;
};

/**
 * Describes the message baepo.api.v1.MachineCreateResponse.
 * Use `create(MachineCreateResponseSchema)` to create a new message.
 */
export declare const MachineCreateResponseSchema: GenMessage<MachineCreateResponse>;

/**
 * @generated from message baepo.api.v1.MachineStartRequest
 */
export declare type MachineStartRequest = Message<"baepo.api.v1.MachineStartRequest"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;
};

/**
 * Describes the message baepo.api.v1.MachineStartRequest.
 * Use `create(MachineStartRequestSchema)` to create a new message.
 */
export declare const MachineStartRequestSchema: GenMessage<MachineStartRequest>;

/**
 * @generated from message baepo.api.v1.MachineStartResponse
 */
export declare type MachineStartResponse = Message<"baepo.api.v1.MachineStartResponse"> & {
  /**
   * @generated from field: baepo.api.v1.Machine machine = 1;
   */
  machine?: Machine;
};

/**
 * Describes the message baepo.api.v1.MachineStartResponse.
 * Use `create(MachineStartResponseSchema)` to create a new message.
 */
export declare const MachineStartResponseSchema: GenMessage<MachineStartResponse>;

/**
 * @generated from message baepo.api.v1.MachineTerminateRequest
 */
export declare type MachineTerminateRequest = Message<"baepo.api.v1.MachineTerminateRequest"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;
};

/**
 * Describes the message baepo.api.v1.MachineTerminateRequest.
 * Use `create(MachineTerminateRequestSchema)` to create a new message.
 */
export declare const MachineTerminateRequestSchema: GenMessage<MachineTerminateRequest>;

/**
 * @generated from message baepo.api.v1.MachineTerminateResponse
 */
export declare type MachineTerminateResponse = Message<"baepo.api.v1.MachineTerminateResponse"> & {
  /**
   * @generated from field: baepo.api.v1.Machine machine = 1;
   */
  machine?: Machine;
};

/**
 * Describes the message baepo.api.v1.MachineTerminateResponse.
 * Use `create(MachineTerminateResponseSchema)` to create a new message.
 */
export declare const MachineTerminateResponseSchema: GenMessage<MachineTerminateResponse>;

/**
 * @generated from message baepo.api.v1.MachineLogsRequest
 */
export declare type MachineLogsRequest = Message<"baepo.api.v1.MachineLogsRequest"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;

  /**
   * @generated from field: optional string container_name = 2;
   */
  containerName?: string;

  /**
   * @generated from field: bool follow = 3;
   */
  follow: boolean;
};

/**
 * Describes the message baepo.api.v1.MachineLogsRequest.
 * Use `create(MachineLogsRequestSchema)` to create a new message.
 */
export declare const MachineLogsRequestSchema: GenMessage<MachineLogsRequest>;

/**
 * @generated from message baepo.api.v1.MachineLogsResponse
 */
export declare type MachineLogsResponse = Message<"baepo.api.v1.MachineLogsResponse"> & {
  /**
   * @generated from field: bool error = 1;
   */
  error: boolean;

  /**
   * @generated from field: string container_name = 2;
   */
  containerName: string;

  /**
   * @generated from field: bytes content = 3;
   */
  content: Uint8Array;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;
};

/**
 * Describes the message baepo.api.v1.MachineLogsResponse.
 * Use `create(MachineLogsResponseSchema)` to create a new message.
 */
export declare const MachineLogsResponseSchema: GenMessage<MachineLogsResponse>;

/**
 * @generated from service baepo.api.v1.MachineService
 */
export declare const MachineService: GenService<{
  /**
   * @generated from rpc baepo.api.v1.MachineService.List
   */
  list: {
    methodKind: "unary";
    input: typeof MachineListRequestSchema;
    output: typeof MachineListResponseSchema;
  },
  /**
   * @generated from rpc baepo.api.v1.MachineService.FindById
   */
  findById: {
    methodKind: "unary";
    input: typeof MachineFindByIdRequestSchema;
    output: typeof MachineFindByIdResponseSchema;
  },
  /**
   * @generated from rpc baepo.api.v1.MachineService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof MachineCreateRequestSchema;
    output: typeof MachineCreateResponseSchema;
  },
  /**
   * @generated from rpc baepo.api.v1.MachineService.Start
   */
  start: {
    methodKind: "unary";
    input: typeof MachineStartRequestSchema;
    output: typeof MachineStartResponseSchema;
  },
  /**
   * @generated from rpc baepo.api.v1.MachineService.Terminate
   */
  terminate: {
    methodKind: "unary";
    input: typeof MachineTerminateRequestSchema;
    output: typeof MachineTerminateResponseSchema;
  },
  /**
   * @generated from rpc baepo.api.v1.MachineService.Logs
   */
  logs: {
    methodKind: "server_streaming";
    input: typeof MachineLogsRequestSchema;
    output: typeof MachineLogsResponseSchema;
  },
}>;

