// @generated by protoc-gen-es v2.2.5
// @generated from file baepo/api/v1/node_controller.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { MachineDesiredState, MachineState } from "../../node/v1/machine_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/node_controller.proto.
 */
export declare const file_baepo_api_v1_node_controller: GenFile;

/**
 * @generated from message baepo.api.v1.NodeControllerServerEvent
 */
export declare type NodeControllerServerEvent = Message<"baepo.api.v1.NodeControllerServerEvent"> & {
  /**
   * @generated from oneof baepo.api.v1.NodeControllerServerEvent.event
   */
  event: {
    /**
     * @generated from field: baepo.api.v1.NodeControllerServerEvent.RegisterResponse register = 1;
     */
    value: NodeControllerServerEvent_RegisterResponse;
    case: "register";
  } | {
    /**
     * @generated from field: baepo.api.v1.NodeControllerServerEvent.PingEvent ping = 2;
     */
    value: NodeControllerServerEvent_PingEvent;
    case: "ping";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message baepo.api.v1.NodeControllerServerEvent.
 * Use `create(NodeControllerServerEventSchema)` to create a new message.
 */
export declare const NodeControllerServerEventSchema: GenMessage<NodeControllerServerEvent>;

/**
 * @generated from message baepo.api.v1.NodeControllerServerEvent.RegisterResponse
 */
export declare type NodeControllerServerEvent_RegisterResponse = Message<"baepo.api.v1.NodeControllerServerEvent.RegisterResponse"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: string node_token = 2;
   */
  nodeToken: string;

  /**
   * @generated from field: bytes authority_cert = 3;
   */
  authorityCert: Uint8Array;

  /**
   * @generated from field: bytes server_cert = 4;
   */
  serverCert: Uint8Array;

  /**
   * @generated from field: bytes server_key = 5;
   */
  serverKey: Uint8Array;
};

/**
 * Describes the message baepo.api.v1.NodeControllerServerEvent.RegisterResponse.
 * Use `create(NodeControllerServerEvent_RegisterResponseSchema)` to create a new message.
 */
export declare const NodeControllerServerEvent_RegisterResponseSchema: GenMessage<NodeControllerServerEvent_RegisterResponse>;

/**
 * @generated from message baepo.api.v1.NodeControllerServerEvent.PingEvent
 */
export declare type NodeControllerServerEvent_PingEvent = Message<"baepo.api.v1.NodeControllerServerEvent.PingEvent"> & {
};

/**
 * Describes the message baepo.api.v1.NodeControllerServerEvent.PingEvent.
 * Use `create(NodeControllerServerEvent_PingEventSchema)` to create a new message.
 */
export declare const NodeControllerServerEvent_PingEventSchema: GenMessage<NodeControllerServerEvent_PingEvent>;

/**
 * @generated from message baepo.api.v1.NodeControllerClientEvent
 */
export declare type NodeControllerClientEvent = Message<"baepo.api.v1.NodeControllerClientEvent"> & {
  /**
   * @generated from oneof baepo.api.v1.NodeControllerClientEvent.event
   */
  event: {
    /**
     * @generated from field: baepo.api.v1.NodeControllerClientEvent.RegisterRequest register = 1;
     */
    value: NodeControllerClientEvent_RegisterRequest;
    case: "register";
  } | {
    /**
     * @generated from field: baepo.api.v1.NodeControllerClientEvent.StatsEvent stats = 2;
     */
    value: NodeControllerClientEvent_StatsEvent;
    case: "stats";
  } | {
    /**
     * @generated from field: baepo.api.v1.NodeControllerClientEvent.MachineStateChangeEvent machine_state_change = 3;
     */
    value: NodeControllerClientEvent_MachineStateChangeEvent;
    case: "machineStateChange";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message baepo.api.v1.NodeControllerClientEvent.
 * Use `create(NodeControllerClientEventSchema)` to create a new message.
 */
export declare const NodeControllerClientEventSchema: GenMessage<NodeControllerClientEvent>;

/**
 * @generated from message baepo.api.v1.NodeControllerClientEvent.RegisterRequest
 */
export declare type NodeControllerClientEvent_RegisterRequest = Message<"baepo.api.v1.NodeControllerClientEvent.RegisterRequest"> & {
  /**
   * @generated from field: string cluster_id = 1;
   */
  clusterId: string;

  /**
   * @generated from field: string bootstrap_token = 2;
   */
  bootstrapToken: string;

  /**
   * @generated from field: optional string node_token = 3;
   */
  nodeToken?: string;

  /**
   * @generated from field: string ip_address = 4;
   */
  ipAddress: string;

  /**
   * @generated from field: string api_endpoint = 5;
   */
  apiEndpoint: string;

  /**
   * @generated from field: string gateway_endpoint = 6;
   */
  gatewayEndpoint: string;
};

/**
 * Describes the message baepo.api.v1.NodeControllerClientEvent.RegisterRequest.
 * Use `create(NodeControllerClientEvent_RegisterRequestSchema)` to create a new message.
 */
export declare const NodeControllerClientEvent_RegisterRequestSchema: GenMessage<NodeControllerClientEvent_RegisterRequest>;

/**
 * @generated from message baepo.api.v1.NodeControllerClientEvent.StatsEvent
 */
export declare type NodeControllerClientEvent_StatsEvent = Message<"baepo.api.v1.NodeControllerClientEvent.StatsEvent"> & {
  /**
   * @generated from field: uint64 total_memory_mb = 1;
   */
  totalMemoryMb: bigint;

  /**
   * @generated from field: uint64 used_memory_mb = 2;
   */
  usedMemoryMb: bigint;

  /**
   * @generated from field: uint64 reserved_memory_mb = 3;
   */
  reservedMemoryMb: bigint;

  /**
   * @generated from field: uint32 cpu_count = 4;
   */
  cpuCount: number;

  /**
   * @generated from field: map<string, baepo.node.v1.MachineState> machine_states = 5;
   */
  machineStates: { [key: string]: MachineState };
};

/**
 * Describes the message baepo.api.v1.NodeControllerClientEvent.StatsEvent.
 * Use `create(NodeControllerClientEvent_StatsEventSchema)` to create a new message.
 */
export declare const NodeControllerClientEvent_StatsEventSchema: GenMessage<NodeControllerClientEvent_StatsEvent>;

/**
 * @generated from message baepo.api.v1.NodeControllerClientEvent.MachineStateChangeEvent
 */
export declare type NodeControllerClientEvent_MachineStateChangeEvent = Message<"baepo.api.v1.NodeControllerClientEvent.MachineStateChangeEvent"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;

  /**
   * @generated from field: baepo.node.v1.MachineState state = 2;
   */
  state: MachineState;

  /**
   * @generated from field: baepo.node.v1.MachineDesiredState desired_state = 3;
   */
  desiredState: MachineDesiredState;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;
};

/**
 * Describes the message baepo.api.v1.NodeControllerClientEvent.MachineStateChangeEvent.
 * Use `create(NodeControllerClientEvent_MachineStateChangeEventSchema)` to create a new message.
 */
export declare const NodeControllerClientEvent_MachineStateChangeEventSchema: GenMessage<NodeControllerClientEvent_MachineStateChangeEvent>;

/**
 * @generated from service baepo.api.v1.NodeControllerService
 */
export declare const NodeControllerService: GenService<{
  /**
   * @generated from rpc baepo.api.v1.NodeControllerService.Events
   */
  events: {
    methodKind: "bidi_streaming";
    input: typeof NodeControllerClientEventSchema;
    output: typeof NodeControllerServerEventSchema;
  },
}>;

