// @generated by protoc-gen-es v2.2.5
// @generated from file baepo/api/v1/node_controller.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/node_controller.proto.
 */
export const file_baepo_api_v1_node_controller = /*@__PURE__*/
  fileDesc("CiJiYWVwby9hcGkvdjEvbm9kZV9jb250cm9sbGVyLnByb3RvEgxiYWVwby5hcGkudjEiswIKFk5vZGVDb25uZWN0U2VydmVyRXZlbnQSSQoIcmVnaXN0ZXIYASABKAsyNS5iYWVwby5hcGkudjEuTm9kZUNvbm5lY3RTZXJ2ZXJFdmVudC5SZWdpc3RlclJlc3BvbnNlSAASPgoEcGluZxgCIAEoCzIuLmJhZXBvLmFwaS52MS5Ob2RlQ29ubmVjdFNlcnZlckV2ZW50LlBpbmdFdmVudEgAGngKEFJlZ2lzdGVyUmVzcG9uc2USDwoHbm9kZV9pZBgBIAEoCRISCgpub2RlX3Rva2VuGAIgASgJEhYKDmF1dGhvcml0eV9jZXJ0GAMgASgMEhMKC3NlcnZlcl9jZXJ0GAQgASgMEhIKCnNlcnZlcl9rZXkYBSABKAwaCwoJUGluZ0V2ZW50QgcKBWV2ZW50It0DChZOb2RlQ29ubmVjdENsaWVudEV2ZW50EkgKCHJlZ2lzdGVyGAEgASgLMjQuYmFlcG8uYXBpLnYxLk5vZGVDb25uZWN0Q2xpZW50RXZlbnQuUmVnaXN0ZXJSZXF1ZXN0SAASQAoFc3RhdHMYAiABKAsyLy5iYWVwby5hcGkudjEuTm9kZUNvbm5lY3RDbGllbnRFdmVudC5TdGF0c0V2ZW50SAAaqgEKD1JlZ2lzdGVyUmVxdWVzdBISCgpjbHVzdGVyX2lkGAEgASgJEhcKD2Jvb3RzdHJhcF90b2tlbhgCIAEoCRIXCgpub2RlX3Rva2VuGAMgASgJSACIAQESEgoKaXBfYWRkcmVzcxgEIAEoCRIUCgxhcGlfZW5kcG9pbnQYBSABKAkSGAoQZ2F0ZXdheV9lbmRwb2ludBgGIAEoCUINCgtfbm9kZV90b2tlbhqAAQoKU3RhdHNFdmVudBIUCgx0b3RhbF9tZW1vcnkYASABKAQSEwoLdXNlZF9tZW1vcnkYAiABKAQSEQoJY3B1X2NvdW50GAMgASgNEhsKE3J1bm5pbmdfbWFjaGluZV9pZHMYBCADKAkSFwoPcmVzZXJ2ZWRfbWVtb3J5GAUgASgEQgcKBWV2ZW50MnIKFU5vZGVDb250cm9sbGVyU2VydmljZRJZCgdDb25uZWN0EiQuYmFlcG8uYXBpLnYxLk5vZGVDb25uZWN0Q2xpZW50RXZlbnQaJC5iYWVwby5hcGkudjEuTm9kZUNvbm5lY3RTZXJ2ZXJFdmVudCgBMAFCNFoyZ2l0aHViLmNvbS9iYWVwby1jbG91ZC9iYWVwby1wcm90by9nby9iYWVwby9hcGkvdjFiBnByb3RvMw", [file_google_protobuf_empty]);

/**
 * Describes the message baepo.api.v1.NodeConnectServerEvent.
 * Use `create(NodeConnectServerEventSchema)` to create a new message.
 */
export const NodeConnectServerEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 0);

/**
 * Describes the message baepo.api.v1.NodeConnectServerEvent.RegisterResponse.
 * Use `create(NodeConnectServerEvent_RegisterResponseSchema)` to create a new message.
 */
export const NodeConnectServerEvent_RegisterResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 0, 0);

/**
 * Describes the message baepo.api.v1.NodeConnectServerEvent.PingEvent.
 * Use `create(NodeConnectServerEvent_PingEventSchema)` to create a new message.
 */
export const NodeConnectServerEvent_PingEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 0, 1);

/**
 * Describes the message baepo.api.v1.NodeConnectClientEvent.
 * Use `create(NodeConnectClientEventSchema)` to create a new message.
 */
export const NodeConnectClientEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 1);

/**
 * Describes the message baepo.api.v1.NodeConnectClientEvent.RegisterRequest.
 * Use `create(NodeConnectClientEvent_RegisterRequestSchema)` to create a new message.
 */
export const NodeConnectClientEvent_RegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 1, 0);

/**
 * Describes the message baepo.api.v1.NodeConnectClientEvent.StatsEvent.
 * Use `create(NodeConnectClientEvent_StatsEventSchema)` to create a new message.
 */
export const NodeConnectClientEvent_StatsEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 1, 1);

/**
 * @generated from service baepo.api.v1.NodeControllerService
 */
export const NodeControllerService = /*@__PURE__*/
  serviceDesc(file_baepo_api_v1_node_controller, 0);

