// @generated by protoc-gen-es v2.2.5
// @generated from file baepo/api/v1/node_controller.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { MachineDesiredState, MachineState } from "../../node/v1/machine_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/node_controller.proto.
 */
export declare const file_baepo_api_v1_node_controller: GenFile;

/**
 * @generated from message baepo.api.v1.NodeControllerServerEvent
 */
export declare type NodeControllerServerEvent = Message<"baepo.api.v1.NodeControllerServerEvent"> & {
  /**
   * @generated from oneof baepo.api.v1.NodeControllerServerEvent.event
   */
  event: {
    /**
     * @generated from field: baepo.api.v1.NodeControllerServerEvent.RegisterResponse register = 1;
     */
    value: NodeControllerServerEvent_RegisterResponse;
    case: "register";
  } | {
    /**
     * @generated from field: baepo.api.v1.NodeControllerServerEvent.Ping ping_event = 2;
     */
    value: NodeControllerServerEvent_Ping;
    case: "pingEvent";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message baepo.api.v1.NodeControllerServerEvent.
 * Use `create(NodeControllerServerEventSchema)` to create a new message.
 */
export declare const NodeControllerServerEventSchema: GenMessage<NodeControllerServerEvent>;

/**
 * @generated from message baepo.api.v1.NodeControllerServerEvent.RegisterResponse
 */
export declare type NodeControllerServerEvent_RegisterResponse = Message<"baepo.api.v1.NodeControllerServerEvent.RegisterResponse"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: string node_token = 2;
   */
  nodeToken: string;

  /**
   * @generated from field: bytes authority_cert = 3;
   */
  authorityCert: Uint8Array;

  /**
   * @generated from field: bytes server_cert = 4;
   */
  serverCert: Uint8Array;

  /**
   * @generated from field: bytes server_key = 5;
   */
  serverKey: Uint8Array;
};

/**
 * Describes the message baepo.api.v1.NodeControllerServerEvent.RegisterResponse.
 * Use `create(NodeControllerServerEvent_RegisterResponseSchema)` to create a new message.
 */
export declare const NodeControllerServerEvent_RegisterResponseSchema: GenMessage<NodeControllerServerEvent_RegisterResponse>;

/**
 * @generated from message baepo.api.v1.NodeControllerServerEvent.Ping
 */
export declare type NodeControllerServerEvent_Ping = Message<"baepo.api.v1.NodeControllerServerEvent.Ping"> & {
};

/**
 * Describes the message baepo.api.v1.NodeControllerServerEvent.Ping.
 * Use `create(NodeControllerServerEvent_PingSchema)` to create a new message.
 */
export declare const NodeControllerServerEvent_PingSchema: GenMessage<NodeControllerServerEvent_Ping>;

/**
 * @generated from message baepo.api.v1.NodeControllerClientEvent
 */
export declare type NodeControllerClientEvent = Message<"baepo.api.v1.NodeControllerClientEvent"> & {
  /**
   * @generated from oneof baepo.api.v1.NodeControllerClientEvent.event
   */
  event: {
    /**
     * @generated from field: baepo.api.v1.NodeControllerClientEvent.RegisterRequest register = 1;
     */
    value: NodeControllerClientEvent_RegisterRequest;
    case: "register";
  } | {
    /**
     * @generated from field: baepo.api.v1.NodeControllerClientEvent.Stats stats_event = 2;
     */
    value: NodeControllerClientEvent_Stats;
    case: "statsEvent";
  } | {
    /**
     * @generated from field: baepo.api.v1.NodeControllerClientEvent.MachineStateChange machine_state_change_event = 3;
     */
    value: NodeControllerClientEvent_MachineStateChange;
    case: "machineStateChangeEvent";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message baepo.api.v1.NodeControllerClientEvent.
 * Use `create(NodeControllerClientEventSchema)` to create a new message.
 */
export declare const NodeControllerClientEventSchema: GenMessage<NodeControllerClientEvent>;

/**
 * @generated from message baepo.api.v1.NodeControllerClientEvent.RegisterRequest
 */
export declare type NodeControllerClientEvent_RegisterRequest = Message<"baepo.api.v1.NodeControllerClientEvent.RegisterRequest"> & {
  /**
   * @generated from field: string cluster_id = 1;
   */
  clusterId: string;

  /**
   * @generated from field: string bootstrap_token = 2;
   */
  bootstrapToken: string;

  /**
   * @generated from field: optional string node_token = 3;
   */
  nodeToken?: string;

  /**
   * @generated from field: string ip_address = 4;
   */
  ipAddress: string;

  /**
   * @generated from field: string api_endpoint = 5;
   */
  apiEndpoint: string;

  /**
   * @generated from field: string gateway_endpoint = 6;
   */
  gatewayEndpoint: string;
};

/**
 * Describes the message baepo.api.v1.NodeControllerClientEvent.RegisterRequest.
 * Use `create(NodeControllerClientEvent_RegisterRequestSchema)` to create a new message.
 */
export declare const NodeControllerClientEvent_RegisterRequestSchema: GenMessage<NodeControllerClientEvent_RegisterRequest>;

/**
 * @generated from message baepo.api.v1.NodeControllerClientEvent.Stats
 */
export declare type NodeControllerClientEvent_Stats = Message<"baepo.api.v1.NodeControllerClientEvent.Stats"> & {
  /**
   * @generated from field: uint64 total_memory_mb = 1;
   */
  totalMemoryMb: bigint;

  /**
   * @generated from field: uint64 used_memory_mb = 2;
   */
  usedMemoryMb: bigint;

  /**
   * @generated from field: uint64 reserved_memory_mb = 3;
   */
  reservedMemoryMb: bigint;

  /**
   * @generated from field: uint32 cpu_count = 4;
   */
  cpuCount: number;
};

/**
 * Describes the message baepo.api.v1.NodeControllerClientEvent.Stats.
 * Use `create(NodeControllerClientEvent_StatsSchema)` to create a new message.
 */
export declare const NodeControllerClientEvent_StatsSchema: GenMessage<NodeControllerClientEvent_Stats>;

/**
 * @generated from message baepo.api.v1.NodeControllerClientEvent.MachineStateChange
 */
export declare type NodeControllerClientEvent_MachineStateChange = Message<"baepo.api.v1.NodeControllerClientEvent.MachineStateChange"> & {
  /**
   * @generated from field: string machine_id = 1;
   */
  machineId: string;

  /**
   * @generated from field: baepo.node.v1.MachineState state = 2;
   */
  state: MachineState;

  /**
   * @generated from field: baepo.node.v1.MachineDesiredState desired_state = 3;
   */
  desiredState: MachineDesiredState;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;
};

/**
 * Describes the message baepo.api.v1.NodeControllerClientEvent.MachineStateChange.
 * Use `create(NodeControllerClientEvent_MachineStateChangeSchema)` to create a new message.
 */
export declare const NodeControllerClientEvent_MachineStateChangeSchema: GenMessage<NodeControllerClientEvent_MachineStateChange>;

/**
 * @generated from service baepo.api.v1.NodeControllerService
 */
export declare const NodeControllerService: GenService<{
  /**
   * @generated from rpc baepo.api.v1.NodeControllerService.Events
   */
  events: {
    methodKind: "bidi_streaming";
    input: typeof NodeControllerClientEventSchema;
    output: typeof NodeControllerServerEventSchema;
  },
}>;

