// @generated by protoc-gen-es v2.2.5
// @generated from file baepo/api/v1/node_controller.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/node_controller.proto.
 */
export const file_baepo_api_v1_node_controller = /*@__PURE__*/
  fileDesc("CiJiYWVwby9hcGkvdjEvbm9kZV9jb250cm9sbGVyLnByb3RvEgxiYWVwby5hcGkudjEi0QIKIE5vZGVDb250cm9sbGVyQ29ubmVjdFNlcnZlckV2ZW50ElMKCHJlZ2lzdGVyGAEgASgLMj8uYmFlcG8uYXBpLnYxLk5vZGVDb250cm9sbGVyQ29ubmVjdFNlcnZlckV2ZW50LlJlZ2lzdGVyUmVzcG9uc2VIABJICgRwaW5nGAIgASgLMjguYmFlcG8uYXBpLnYxLk5vZGVDb250cm9sbGVyQ29ubmVjdFNlcnZlckV2ZW50LlBpbmdFdmVudEgAGngKEFJlZ2lzdGVyUmVzcG9uc2USDwoHbm9kZV9pZBgBIAEoCRISCgpub2RlX3Rva2VuGAIgASgJEhYKDmF1dGhvcml0eV9jZXJ0GAMgASgMEhMKC3NlcnZlcl9jZXJ0GAQgASgMEhIKCnNlcnZlcl9rZXkYBSABKAwaCwoJUGluZ0V2ZW50QgcKBWV2ZW50IvsDCiBOb2RlQ29udHJvbGxlckNvbm5lY3RDbGllbnRFdmVudBJSCghyZWdpc3RlchgBIAEoCzI+LmJhZXBvLmFwaS52MS5Ob2RlQ29udHJvbGxlckNvbm5lY3RDbGllbnRFdmVudC5SZWdpc3RlclJlcXVlc3RIABJKCgVzdGF0cxgCIAEoCzI5LmJhZXBvLmFwaS52MS5Ob2RlQ29udHJvbGxlckNvbm5lY3RDbGllbnRFdmVudC5TdGF0c0V2ZW50SAAaqgEKD1JlZ2lzdGVyUmVxdWVzdBISCgpjbHVzdGVyX2lkGAEgASgJEhcKD2Jvb3RzdHJhcF90b2tlbhgCIAEoCRIXCgpub2RlX3Rva2VuGAMgASgJSACIAQESEgoKaXBfYWRkcmVzcxgEIAEoCRIUCgxhcGlfZW5kcG9pbnQYBSABKAkSGAoQZ2F0ZXdheV9lbmRwb2ludBgGIAEoCUINCgtfbm9kZV90b2tlbhqAAQoKU3RhdHNFdmVudBIUCgx0b3RhbF9tZW1vcnkYASABKAQSEwoLdXNlZF9tZW1vcnkYAiABKAQSEQoJY3B1X2NvdW50GAMgASgNEhsKE3J1bm5pbmdfbWFjaGluZV9pZHMYBCADKAkSFwoPcmVzZXJ2ZWRfbWVtb3J5GAUgASgEQgcKBWV2ZW50MoYBChVOb2RlQ29udHJvbGxlclNlcnZpY2USbQoHQ29ubmVjdBIuLmJhZXBvLmFwaS52MS5Ob2RlQ29udHJvbGxlckNvbm5lY3RDbGllbnRFdmVudBouLmJhZXBvLmFwaS52MS5Ob2RlQ29udHJvbGxlckNvbm5lY3RTZXJ2ZXJFdmVudCgBMAFCNFoyZ2l0aHViLmNvbS9iYWVwby1jbG91ZC9iYWVwby1wcm90by9nby9iYWVwby9hcGkvdjFiBnByb3RvMw", [file_google_protobuf_empty]);

/**
 * Describes the message baepo.api.v1.NodeControllerConnectServerEvent.
 * Use `create(NodeControllerConnectServerEventSchema)` to create a new message.
 */
export const NodeControllerConnectServerEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 0);

/**
 * Describes the message baepo.api.v1.NodeControllerConnectServerEvent.RegisterResponse.
 * Use `create(NodeControllerConnectServerEvent_RegisterResponseSchema)` to create a new message.
 */
export const NodeControllerConnectServerEvent_RegisterResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 0, 0);

/**
 * Describes the message baepo.api.v1.NodeControllerConnectServerEvent.PingEvent.
 * Use `create(NodeControllerConnectServerEvent_PingEventSchema)` to create a new message.
 */
export const NodeControllerConnectServerEvent_PingEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 0, 1);

/**
 * Describes the message baepo.api.v1.NodeControllerConnectClientEvent.
 * Use `create(NodeControllerConnectClientEventSchema)` to create a new message.
 */
export const NodeControllerConnectClientEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 1);

/**
 * Describes the message baepo.api.v1.NodeControllerConnectClientEvent.RegisterRequest.
 * Use `create(NodeControllerConnectClientEvent_RegisterRequestSchema)` to create a new message.
 */
export const NodeControllerConnectClientEvent_RegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 1, 0);

/**
 * Describes the message baepo.api.v1.NodeControllerConnectClientEvent.StatsEvent.
 * Use `create(NodeControllerConnectClientEvent_StatsEventSchema)` to create a new message.
 */
export const NodeControllerConnectClientEvent_StatsEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node_controller, 1, 1);

/**
 * @generated from service baepo.api.v1.NodeControllerService
 */
export const NodeControllerService = /*@__PURE__*/
  serviceDesc(file_baepo_api_v1_node_controller, 0);

