// @generated by protoc-gen-es v2.2.5
// @generated from file baepo/api/v1/node.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/node.proto.
 */
export const file_baepo_api_v1_node = /*@__PURE__*/
  fileDesc("ChdiYWVwby9hcGkvdjEvbm9kZS5wcm90bxIMYmFlcG8uYXBpLnYxIrMCChZOb2RlQ29ubmVjdFNlcnZlckV2ZW50EkkKCHJlZ2lzdGVyGAEgASgLMjUuYmFlcG8uYXBpLnYxLk5vZGVDb25uZWN0U2VydmVyRXZlbnQuUmVnaXN0ZXJSZXNwb25zZUgAEj4KBHBpbmcYAiABKAsyLi5iYWVwby5hcGkudjEuTm9kZUNvbm5lY3RTZXJ2ZXJFdmVudC5QaW5nRXZlbnRIABp4ChBSZWdpc3RlclJlc3BvbnNlEg8KB25vZGVfaWQYASABKAkSEgoKbm9kZV90b2tlbhgCIAEoCRIWCg5hdXRob3JpdHlfY2VydBgDIAEoDBITCgtzZXJ2ZXJfY2VydBgEIAEoDBISCgpzZXJ2ZXJfa2V5GAUgASgMGgsKCVBpbmdFdmVudEIHCgVldmVudCLdAwoWTm9kZUNvbm5lY3RDbGllbnRFdmVudBJICghyZWdpc3RlchgBIAEoCzI0LmJhZXBvLmFwaS52MS5Ob2RlQ29ubmVjdENsaWVudEV2ZW50LlJlZ2lzdGVyUmVxdWVzdEgAEkAKBXN0YXRzGAIgASgLMi8uYmFlcG8uYXBpLnYxLk5vZGVDb25uZWN0Q2xpZW50RXZlbnQuU3RhdHNFdmVudEgAGqoBCg9SZWdpc3RlclJlcXVlc3QSEgoKY2x1c3Rlcl9pZBgBIAEoCRIXCg9ib290c3RyYXBfdG9rZW4YAiABKAkSFwoKbm9kZV90b2tlbhgDIAEoCUgAiAEBEhIKCmlwX2FkZHJlc3MYBCABKAkSFAoMYXBpX2VuZHBvaW50GAUgASgJEhgKEGdhdGV3YXlfZW5kcG9pbnQYBiABKAlCDQoLX25vZGVfdG9rZW4agAEKClN0YXRzRXZlbnQSFAoMdG90YWxfbWVtb3J5GAEgASgEEhMKC3VzZWRfbWVtb3J5GAIgASgEEhEKCWNwdV9jb3VudBgDIAEoDRIbChNydW5uaW5nX21hY2hpbmVfaWRzGAQgAygJEhcKD3Jlc2VydmVkX21lbW9yeRgFIAEoBEIHCgVldmVudDJoCgtOb2RlU2VydmljZRJZCgdDb25uZWN0EiQuYmFlcG8uYXBpLnYxLk5vZGVDb25uZWN0Q2xpZW50RXZlbnQaJC5iYWVwby5hcGkudjEuTm9kZUNvbm5lY3RTZXJ2ZXJFdmVudCgBMAFCNFoyZ2l0aHViLmNvbS9iYWVwby1jbG91ZC9iYWVwby1wcm90by9nby9iYWVwby9hcGkvdjFiBnByb3RvMw", [file_google_protobuf_empty]);

/**
 * Describes the message baepo.api.v1.NodeConnectServerEvent.
 * Use `create(NodeConnectServerEventSchema)` to create a new message.
 */
export const NodeConnectServerEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node, 0);

/**
 * Describes the message baepo.api.v1.NodeConnectServerEvent.RegisterResponse.
 * Use `create(NodeConnectServerEvent_RegisterResponseSchema)` to create a new message.
 */
export const NodeConnectServerEvent_RegisterResponseSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node, 0, 0);

/**
 * Describes the message baepo.api.v1.NodeConnectServerEvent.PingEvent.
 * Use `create(NodeConnectServerEvent_PingEventSchema)` to create a new message.
 */
export const NodeConnectServerEvent_PingEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node, 0, 1);

/**
 * Describes the message baepo.api.v1.NodeConnectClientEvent.
 * Use `create(NodeConnectClientEventSchema)` to create a new message.
 */
export const NodeConnectClientEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node, 1);

/**
 * Describes the message baepo.api.v1.NodeConnectClientEvent.RegisterRequest.
 * Use `create(NodeConnectClientEvent_RegisterRequestSchema)` to create a new message.
 */
export const NodeConnectClientEvent_RegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node, 1, 0);

/**
 * Describes the message baepo.api.v1.NodeConnectClientEvent.StatsEvent.
 * Use `create(NodeConnectClientEvent_StatsEventSchema)` to create a new message.
 */
export const NodeConnectClientEvent_StatsEventSchema = /*@__PURE__*/
  messageDesc(file_baepo_api_v1_node, 1, 1);

/**
 * @generated from service baepo.api.v1.NodeService
 */
export const NodeService = /*@__PURE__*/
  serviceDesc(file_baepo_api_v1_node, 0);

