// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=js"
// @generated from file baepo/api/v1/user.proto (package baepo.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file baepo/api/v1/user.proto.
 */
export declare const file_baepo_api_v1_user: GenFile;

/**
 * @generated from message baepo.api.v1.User
 */
export declare type User = Message<"baepo.api.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string first_name = 3;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 4;
   */
  lastName: string;

  /**
   * @generated from field: bool admin = 5;
   */
  admin: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string workspace_id = 7;
   */
  workspaceId: string;
};

/**
 * Describes the message baepo.api.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export declare const UserSchema: GenMessage<User>;

/**
 * @generated from message baepo.api.v1.UserMeResponse
 */
export declare type UserMeResponse = Message<"baepo.api.v1.UserMeResponse"> & {
  /**
   * @generated from field: baepo.api.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message baepo.api.v1.UserMeResponse.
 * Use `create(UserMeResponseSchema)` to create a new message.
 */
export declare const UserMeResponseSchema: GenMessage<UserMeResponse>;

/**
 * @generated from service baepo.api.v1.UserService
 */
export declare const UserService: GenService<{
  /**
   * @generated from rpc baepo.api.v1.UserService.Me
   */
  me: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof UserMeResponseSchema;
  },
}>;

