// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/api/v1/cluster.proto

package apiv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cluster struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BootstrapToken *string                `protobuf:"bytes,3,opt,name=bootstrap_token,json=bootstrapToken,proto3,oneof" json:"bootstrap_token,omitempty"`
	CanManage      bool                   `protobuf:"varint,4,opt,name=can_manage,json=canManage,proto3" json:"can_manage,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	WorkspaceId    *string                `protobuf:"bytes,8,opt,name=workspace_id,json=workspaceId,proto3,oneof" json:"workspace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetBootstrapToken() string {
	if x != nil && x.BootstrapToken != nil {
		return *x.BootstrapToken
	}
	return ""
}

func (x *Cluster) GetCanManage() bool {
	if x != nil {
		return x.CanManage
	}
	return false
}

func (x *Cluster) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cluster) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Cluster) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Cluster) GetWorkspaceId() string {
	if x != nil && x.WorkspaceId != nil {
		return *x.WorkspaceId
	}
	return ""
}

type ClusterListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterListRequest) Reset() {
	*x = ClusterListRequest{}
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterListRequest) ProtoMessage() {}

func (x *ClusterListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterListRequest.ProtoReflect.Descriptor instead.
func (*ClusterListRequest) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterListRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ClusterListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterListResponse) Reset() {
	*x = ClusterListResponse{}
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterListResponse) ProtoMessage() {}

func (x *ClusterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterListResponse.ProtoReflect.Descriptor instead.
func (*ClusterListResponse) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterListResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type ClusterCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterCreateRequest) Reset() {
	*x = ClusterCreateRequest{}
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCreateRequest) ProtoMessage() {}

func (x *ClusterCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterCreateRequest.ProtoReflect.Descriptor instead.
func (*ClusterCreateRequest) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ClusterCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterCreateResponse) Reset() {
	*x = ClusterCreateResponse{}
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCreateResponse) ProtoMessage() {}

func (x *ClusterCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterCreateResponse.ProtoReflect.Descriptor instead.
func (*ClusterCreateResponse) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterCreateResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type ClusterDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterDeleteRequest) Reset() {
	*x = ClusterDeleteRequest{}
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterDeleteRequest) ProtoMessage() {}

func (x *ClusterDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterDeleteRequest.ProtoReflect.Descriptor instead.
func (*ClusterDeleteRequest) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterDeleteRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ClusterDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterDeleteResponse) Reset() {
	*x = ClusterDeleteResponse{}
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterDeleteResponse) ProtoMessage() {}

func (x *ClusterDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterDeleteResponse.ProtoReflect.Descriptor instead.
func (*ClusterDeleteResponse) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterDeleteResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

var File_baepo_api_v1_cluster_proto protoreflect.FileDescriptor

const file_baepo_api_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1abaepo/api/v1/cluster.proto\x12\fbaepo.api.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x03\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x0fbootstrap_token\x18\x03 \x01(\tH\x00R\x0ebootstrapToken\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"can_manage\x18\x04 \x01(\bR\tcanManage\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdeletedAt\x88\x01\x01\x12&\n" +
	"\fworkspace_id\x18\b \x01(\tH\x02R\vworkspaceId\x88\x01\x01B\x12\n" +
	"\x10_bootstrap_tokenB\r\n" +
	"\v_deleted_atB\x0f\n" +
	"\r_workspace_id\"7\n" +
	"\x12ClusterListRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"H\n" +
	"\x13ClusterListResponse\x121\n" +
	"\bclusters\x18\x01 \x03(\v2\x15.baepo.api.v1.ClusterR\bclusters\"*\n" +
	"\x14ClusterCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x15ClusterCreateResponse\x12/\n" +
	"\acluster\x18\x01 \x01(\v2\x15.baepo.api.v1.ClusterR\acluster\"5\n" +
	"\x14ClusterDeleteRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"H\n" +
	"\x15ClusterDeleteResponse\x12/\n" +
	"\acluster\x18\x01 \x01(\v2\x15.baepo.api.v1.ClusterR\acluster2\x83\x02\n" +
	"\x0eClusterService\x12K\n" +
	"\x04List\x12 .baepo.api.v1.ClusterListRequest\x1a!.baepo.api.v1.ClusterListResponse\x12Q\n" +
	"\x06Create\x12\".baepo.api.v1.ClusterCreateRequest\x1a#.baepo.api.v1.ClusterCreateResponse\x12Q\n" +
	"\x06Delete\x12\".baepo.api.v1.ClusterDeleteRequest\x1a#.baepo.api.v1.ClusterDeleteResponseB<Z:github.com/baepo-cloud/baepo-proto/go/baepo/api/v1;apiv1pbb\x06proto3"

var (
	file_baepo_api_v1_cluster_proto_rawDescOnce sync.Once
	file_baepo_api_v1_cluster_proto_rawDescData []byte
)

func file_baepo_api_v1_cluster_proto_rawDescGZIP() []byte {
	file_baepo_api_v1_cluster_proto_rawDescOnce.Do(func() {
		file_baepo_api_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baepo_api_v1_cluster_proto_rawDesc), len(file_baepo_api_v1_cluster_proto_rawDesc)))
	})
	return file_baepo_api_v1_cluster_proto_rawDescData
}

var file_baepo_api_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_baepo_api_v1_cluster_proto_goTypes = []any{
	(*Cluster)(nil),               // 0: baepo.api.v1.Cluster
	(*ClusterListRequest)(nil),    // 1: baepo.api.v1.ClusterListRequest
	(*ClusterListResponse)(nil),   // 2: baepo.api.v1.ClusterListResponse
	(*ClusterCreateRequest)(nil),  // 3: baepo.api.v1.ClusterCreateRequest
	(*ClusterCreateResponse)(nil), // 4: baepo.api.v1.ClusterCreateResponse
	(*ClusterDeleteRequest)(nil),  // 5: baepo.api.v1.ClusterDeleteRequest
	(*ClusterDeleteResponse)(nil), // 6: baepo.api.v1.ClusterDeleteResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_baepo_api_v1_cluster_proto_depIdxs = []int32{
	7, // 0: baepo.api.v1.Cluster.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: baepo.api.v1.Cluster.updated_at:type_name -> google.protobuf.Timestamp
	7, // 2: baepo.api.v1.Cluster.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 3: baepo.api.v1.ClusterListResponse.clusters:type_name -> baepo.api.v1.Cluster
	0, // 4: baepo.api.v1.ClusterCreateResponse.cluster:type_name -> baepo.api.v1.Cluster
	0, // 5: baepo.api.v1.ClusterDeleteResponse.cluster:type_name -> baepo.api.v1.Cluster
	1, // 6: baepo.api.v1.ClusterService.List:input_type -> baepo.api.v1.ClusterListRequest
	3, // 7: baepo.api.v1.ClusterService.Create:input_type -> baepo.api.v1.ClusterCreateRequest
	5, // 8: baepo.api.v1.ClusterService.Delete:input_type -> baepo.api.v1.ClusterDeleteRequest
	2, // 9: baepo.api.v1.ClusterService.List:output_type -> baepo.api.v1.ClusterListResponse
	4, // 10: baepo.api.v1.ClusterService.Create:output_type -> baepo.api.v1.ClusterCreateResponse
	6, // 11: baepo.api.v1.ClusterService.Delete:output_type -> baepo.api.v1.ClusterDeleteResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_baepo_api_v1_cluster_proto_init() }
func file_baepo_api_v1_cluster_proto_init() {
	if File_baepo_api_v1_cluster_proto != nil {
		return
	}
	file_baepo_api_v1_cluster_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_api_v1_cluster_proto_rawDesc), len(file_baepo_api_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baepo_api_v1_cluster_proto_goTypes,
		DependencyIndexes: file_baepo_api_v1_cluster_proto_depIdxs,
		MessageInfos:      file_baepo_api_v1_cluster_proto_msgTypes,
	}.Build()
	File_baepo_api_v1_cluster_proto = out.File
	file_baepo_api_v1_cluster_proto_goTypes = nil
	file_baepo_api_v1_cluster_proto_depIdxs = nil
}
