// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/api/v1/node_controller.proto

package v1

import (
	v1 "github.com/baepo-cloud/baepo-proto/go/baepo/node/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeControllerServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*NodeControllerServerEvent_Register
	//	*NodeControllerServerEvent_PingEvent
	Event         isNodeControllerServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeControllerServerEvent) Reset() {
	*x = NodeControllerServerEvent{}
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeControllerServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeControllerServerEvent) ProtoMessage() {}

func (x *NodeControllerServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeControllerServerEvent.ProtoReflect.Descriptor instead.
func (*NodeControllerServerEvent) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_node_controller_proto_rawDescGZIP(), []int{0}
}

func (x *NodeControllerServerEvent) GetEvent() isNodeControllerServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NodeControllerServerEvent) GetRegister() *NodeControllerServerEvent_RegisterResponse {
	if x != nil {
		if x, ok := x.Event.(*NodeControllerServerEvent_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *NodeControllerServerEvent) GetPingEvent() *NodeControllerServerEvent_Ping {
	if x != nil {
		if x, ok := x.Event.(*NodeControllerServerEvent_PingEvent); ok {
			return x.PingEvent
		}
	}
	return nil
}

type isNodeControllerServerEvent_Event interface {
	isNodeControllerServerEvent_Event()
}

type NodeControllerServerEvent_Register struct {
	Register *NodeControllerServerEvent_RegisterResponse `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type NodeControllerServerEvent_PingEvent struct {
	PingEvent *NodeControllerServerEvent_Ping `protobuf:"bytes,2,opt,name=ping_event,json=pingEvent,proto3,oneof"`
}

func (*NodeControllerServerEvent_Register) isNodeControllerServerEvent_Event() {}

func (*NodeControllerServerEvent_PingEvent) isNodeControllerServerEvent_Event() {}

type NodeControllerClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*NodeControllerClientEvent_Register
	//	*NodeControllerClientEvent_StatsEvent
	//	*NodeControllerClientEvent_MachineStateChangeEvent
	Event         isNodeControllerClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeControllerClientEvent) Reset() {
	*x = NodeControllerClientEvent{}
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeControllerClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeControllerClientEvent) ProtoMessage() {}

func (x *NodeControllerClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeControllerClientEvent.ProtoReflect.Descriptor instead.
func (*NodeControllerClientEvent) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_node_controller_proto_rawDescGZIP(), []int{1}
}

func (x *NodeControllerClientEvent) GetEvent() isNodeControllerClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NodeControllerClientEvent) GetRegister() *NodeControllerClientEvent_RegisterRequest {
	if x != nil {
		if x, ok := x.Event.(*NodeControllerClientEvent_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *NodeControllerClientEvent) GetStatsEvent() *NodeControllerClientEvent_Stats {
	if x != nil {
		if x, ok := x.Event.(*NodeControllerClientEvent_StatsEvent); ok {
			return x.StatsEvent
		}
	}
	return nil
}

func (x *NodeControllerClientEvent) GetMachineStateChangeEvent() *NodeControllerClientEvent_MachineStateChange {
	if x != nil {
		if x, ok := x.Event.(*NodeControllerClientEvent_MachineStateChangeEvent); ok {
			return x.MachineStateChangeEvent
		}
	}
	return nil
}

type isNodeControllerClientEvent_Event interface {
	isNodeControllerClientEvent_Event()
}

type NodeControllerClientEvent_Register struct {
	Register *NodeControllerClientEvent_RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type NodeControllerClientEvent_StatsEvent struct {
	StatsEvent *NodeControllerClientEvent_Stats `protobuf:"bytes,2,opt,name=stats_event,json=statsEvent,proto3,oneof"`
}

type NodeControllerClientEvent_MachineStateChangeEvent struct {
	MachineStateChangeEvent *NodeControllerClientEvent_MachineStateChange `protobuf:"bytes,3,opt,name=machine_state_change_event,json=machineStateChangeEvent,proto3,oneof"`
}

func (*NodeControllerClientEvent_Register) isNodeControllerClientEvent_Event() {}

func (*NodeControllerClientEvent_StatsEvent) isNodeControllerClientEvent_Event() {}

func (*NodeControllerClientEvent_MachineStateChangeEvent) isNodeControllerClientEvent_Event() {}

type NodeControllerServerEvent_RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeToken     string                 `protobuf:"bytes,2,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	AuthorityCert []byte                 `protobuf:"bytes,3,opt,name=authority_cert,json=authorityCert,proto3" json:"authority_cert,omitempty"`
	ServerCert    []byte                 `protobuf:"bytes,4,opt,name=server_cert,json=serverCert,proto3" json:"server_cert,omitempty"`
	ServerKey     []byte                 `protobuf:"bytes,5,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeControllerServerEvent_RegisterResponse) Reset() {
	*x = NodeControllerServerEvent_RegisterResponse{}
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeControllerServerEvent_RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeControllerServerEvent_RegisterResponse) ProtoMessage() {}

func (x *NodeControllerServerEvent_RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeControllerServerEvent_RegisterResponse.ProtoReflect.Descriptor instead.
func (*NodeControllerServerEvent_RegisterResponse) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_node_controller_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NodeControllerServerEvent_RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeControllerServerEvent_RegisterResponse) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *NodeControllerServerEvent_RegisterResponse) GetAuthorityCert() []byte {
	if x != nil {
		return x.AuthorityCert
	}
	return nil
}

func (x *NodeControllerServerEvent_RegisterResponse) GetServerCert() []byte {
	if x != nil {
		return x.ServerCert
	}
	return nil
}

func (x *NodeControllerServerEvent_RegisterResponse) GetServerKey() []byte {
	if x != nil {
		return x.ServerKey
	}
	return nil
}

type NodeControllerServerEvent_Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeControllerServerEvent_Ping) Reset() {
	*x = NodeControllerServerEvent_Ping{}
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeControllerServerEvent_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeControllerServerEvent_Ping) ProtoMessage() {}

func (x *NodeControllerServerEvent_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeControllerServerEvent_Ping.ProtoReflect.Descriptor instead.
func (*NodeControllerServerEvent_Ping) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_node_controller_proto_rawDescGZIP(), []int{0, 1}
}

type NodeControllerClientEvent_RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterId       string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	BootstrapToken  string                 `protobuf:"bytes,2,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	NodeToken       *string                `protobuf:"bytes,3,opt,name=node_token,json=nodeToken,proto3,oneof" json:"node_token,omitempty"`
	IpAddress       string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ApiEndpoint     string                 `protobuf:"bytes,5,opt,name=api_endpoint,json=apiEndpoint,proto3" json:"api_endpoint,omitempty"`
	GatewayEndpoint string                 `protobuf:"bytes,6,opt,name=gateway_endpoint,json=gatewayEndpoint,proto3" json:"gateway_endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeControllerClientEvent_RegisterRequest) Reset() {
	*x = NodeControllerClientEvent_RegisterRequest{}
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeControllerClientEvent_RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeControllerClientEvent_RegisterRequest) ProtoMessage() {}

func (x *NodeControllerClientEvent_RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeControllerClientEvent_RegisterRequest.ProtoReflect.Descriptor instead.
func (*NodeControllerClientEvent_RegisterRequest) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_node_controller_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NodeControllerClientEvent_RegisterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeControllerClientEvent_RegisterRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *NodeControllerClientEvent_RegisterRequest) GetNodeToken() string {
	if x != nil && x.NodeToken != nil {
		return *x.NodeToken
	}
	return ""
}

func (x *NodeControllerClientEvent_RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NodeControllerClientEvent_RegisterRequest) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *NodeControllerClientEvent_RegisterRequest) GetGatewayEndpoint() string {
	if x != nil {
		return x.GatewayEndpoint
	}
	return ""
}

type NodeControllerClientEvent_Stats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalMemoryMb    uint64                 `protobuf:"varint,1,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	UsedMemoryMb     uint64                 `protobuf:"varint,2,opt,name=used_memory_mb,json=usedMemoryMb,proto3" json:"used_memory_mb,omitempty"`
	ReservedMemoryMb uint64                 `protobuf:"varint,3,opt,name=reserved_memory_mb,json=reservedMemoryMb,proto3" json:"reserved_memory_mb,omitempty"`
	CpuCount         uint32                 `protobuf:"varint,4,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeControllerClientEvent_Stats) Reset() {
	*x = NodeControllerClientEvent_Stats{}
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeControllerClientEvent_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeControllerClientEvent_Stats) ProtoMessage() {}

func (x *NodeControllerClientEvent_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeControllerClientEvent_Stats.ProtoReflect.Descriptor instead.
func (*NodeControllerClientEvent_Stats) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_node_controller_proto_rawDescGZIP(), []int{1, 1}
}

func (x *NodeControllerClientEvent_Stats) GetTotalMemoryMb() uint64 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *NodeControllerClientEvent_Stats) GetUsedMemoryMb() uint64 {
	if x != nil {
		return x.UsedMemoryMb
	}
	return 0
}

func (x *NodeControllerClientEvent_Stats) GetReservedMemoryMb() uint64 {
	if x != nil {
		return x.ReservedMemoryMb
	}
	return 0
}

func (x *NodeControllerClientEvent_Stats) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

type NodeControllerClientEvent_MachineStateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	State         v1.MachineState        `protobuf:"varint,2,opt,name=state,proto3,enum=baepo.node.v1.MachineState" json:"state,omitempty"`
	DesiredState  v1.MachineDesiredState `protobuf:"varint,3,opt,name=desired_state,json=desiredState,proto3,enum=baepo.node.v1.MachineDesiredState" json:"desired_state,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeControllerClientEvent_MachineStateChange) Reset() {
	*x = NodeControllerClientEvent_MachineStateChange{}
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeControllerClientEvent_MachineStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeControllerClientEvent_MachineStateChange) ProtoMessage() {}

func (x *NodeControllerClientEvent_MachineStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_node_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeControllerClientEvent_MachineStateChange.ProtoReflect.Descriptor instead.
func (*NodeControllerClientEvent_MachineStateChange) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_node_controller_proto_rawDescGZIP(), []int{1, 2}
}

func (x *NodeControllerClientEvent_MachineStateChange) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *NodeControllerClientEvent_MachineStateChange) GetState() v1.MachineState {
	if x != nil {
		return x.State
	}
	return v1.MachineState(0)
}

func (x *NodeControllerClientEvent_MachineStateChange) GetDesiredState() v1.MachineDesiredState {
	if x != nil {
		return x.DesiredState
	}
	return v1.MachineDesiredState(0)
}

func (x *NodeControllerClientEvent_MachineStateChange) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_baepo_api_v1_node_controller_proto protoreflect.FileDescriptor

const file_baepo_api_v1_node_controller_proto_rawDesc = "" +
	"\n" +
	"\"baepo/api/v1/node_controller.proto\x12\fbaepo.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbaepo/node/v1/machine.proto\"\x87\x03\n" +
	"\x19NodeControllerServerEvent\x12V\n" +
	"\bregister\x18\x01 \x01(\v28.baepo.api.v1.NodeControllerServerEvent.RegisterResponseH\x00R\bregister\x12M\n" +
	"\n" +
	"ping_event\x18\x02 \x01(\v2,.baepo.api.v1.NodeControllerServerEvent.PingH\x00R\tpingEvent\x1a\xb1\x01\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"node_token\x18\x02 \x01(\tR\tnodeToken\x12%\n" +
	"\x0eauthority_cert\x18\x03 \x01(\fR\rauthorityCert\x12\x1f\n" +
	"\vserver_cert\x18\x04 \x01(\fR\n" +
	"serverCert\x12\x1d\n" +
	"\n" +
	"server_key\x18\x05 \x01(\fR\tserverKey\x1a\x06\n" +
	"\x04PingB\a\n" +
	"\x05event\"\xd3\a\n" +
	"\x19NodeControllerClientEvent\x12U\n" +
	"\bregister\x18\x01 \x01(\v27.baepo.api.v1.NodeControllerClientEvent.RegisterRequestH\x00R\bregister\x12P\n" +
	"\vstats_event\x18\x02 \x01(\v2-.baepo.api.v1.NodeControllerClientEvent.StatsH\x00R\n" +
	"statsEvent\x12y\n" +
	"\x1amachine_state_change_event\x18\x03 \x01(\v2:.baepo.api.v1.NodeControllerClientEvent.MachineStateChangeH\x00R\x17machineStateChangeEvent\x1a\xf9\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12'\n" +
	"\x0fbootstrap_token\x18\x02 \x01(\tR\x0ebootstrapToken\x12\"\n" +
	"\n" +
	"node_token\x18\x03 \x01(\tH\x00R\tnodeToken\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12!\n" +
	"\fapi_endpoint\x18\x05 \x01(\tR\vapiEndpoint\x12)\n" +
	"\x10gateway_endpoint\x18\x06 \x01(\tR\x0fgatewayEndpointB\r\n" +
	"\v_node_token\x1a\xa0\x01\n" +
	"\x05Stats\x12&\n" +
	"\x0ftotal_memory_mb\x18\x01 \x01(\x04R\rtotalMemoryMb\x12$\n" +
	"\x0eused_memory_mb\x18\x02 \x01(\x04R\fusedMemoryMb\x12,\n" +
	"\x12reserved_memory_mb\x18\x03 \x01(\x04R\x10reservedMemoryMb\x12\x1b\n" +
	"\tcpu_count\x18\x04 \x01(\rR\bcpuCount\x1a\xe9\x01\n" +
	"\x12MachineStateChange\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x121\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1b.baepo.node.v1.MachineStateR\x05state\x12G\n" +
	"\rdesired_state\x18\x03 \x01(\x0e2\".baepo.node.v1.MachineDesiredStateR\fdesiredState\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\a\n" +
	"\x05event2w\n" +
	"\x15NodeControllerService\x12^\n" +
	"\x06Events\x12'.baepo.api.v1.NodeControllerClientEvent\x1a'.baepo.api.v1.NodeControllerServerEvent(\x010\x01B4Z2github.com/baepo-cloud/baepo-proto/go/baepo/api/v1b\x06proto3"

var (
	file_baepo_api_v1_node_controller_proto_rawDescOnce sync.Once
	file_baepo_api_v1_node_controller_proto_rawDescData []byte
)

func file_baepo_api_v1_node_controller_proto_rawDescGZIP() []byte {
	file_baepo_api_v1_node_controller_proto_rawDescOnce.Do(func() {
		file_baepo_api_v1_node_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baepo_api_v1_node_controller_proto_rawDesc), len(file_baepo_api_v1_node_controller_proto_rawDesc)))
	})
	return file_baepo_api_v1_node_controller_proto_rawDescData
}

var file_baepo_api_v1_node_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_baepo_api_v1_node_controller_proto_goTypes = []any{
	(*NodeControllerServerEvent)(nil),                    // 0: baepo.api.v1.NodeControllerServerEvent
	(*NodeControllerClientEvent)(nil),                    // 1: baepo.api.v1.NodeControllerClientEvent
	(*NodeControllerServerEvent_RegisterResponse)(nil),   // 2: baepo.api.v1.NodeControllerServerEvent.RegisterResponse
	(*NodeControllerServerEvent_Ping)(nil),               // 3: baepo.api.v1.NodeControllerServerEvent.Ping
	(*NodeControllerClientEvent_RegisterRequest)(nil),    // 4: baepo.api.v1.NodeControllerClientEvent.RegisterRequest
	(*NodeControllerClientEvent_Stats)(nil),              // 5: baepo.api.v1.NodeControllerClientEvent.Stats
	(*NodeControllerClientEvent_MachineStateChange)(nil), // 6: baepo.api.v1.NodeControllerClientEvent.MachineStateChange
	(v1.MachineState)(0),                                 // 7: baepo.node.v1.MachineState
	(v1.MachineDesiredState)(0),                          // 8: baepo.node.v1.MachineDesiredState
	(*timestamppb.Timestamp)(nil),                        // 9: google.protobuf.Timestamp
}
var file_baepo_api_v1_node_controller_proto_depIdxs = []int32{
	2, // 0: baepo.api.v1.NodeControllerServerEvent.register:type_name -> baepo.api.v1.NodeControllerServerEvent.RegisterResponse
	3, // 1: baepo.api.v1.NodeControllerServerEvent.ping_event:type_name -> baepo.api.v1.NodeControllerServerEvent.Ping
	4, // 2: baepo.api.v1.NodeControllerClientEvent.register:type_name -> baepo.api.v1.NodeControllerClientEvent.RegisterRequest
	5, // 3: baepo.api.v1.NodeControllerClientEvent.stats_event:type_name -> baepo.api.v1.NodeControllerClientEvent.Stats
	6, // 4: baepo.api.v1.NodeControllerClientEvent.machine_state_change_event:type_name -> baepo.api.v1.NodeControllerClientEvent.MachineStateChange
	7, // 5: baepo.api.v1.NodeControllerClientEvent.MachineStateChange.state:type_name -> baepo.node.v1.MachineState
	8, // 6: baepo.api.v1.NodeControllerClientEvent.MachineStateChange.desired_state:type_name -> baepo.node.v1.MachineDesiredState
	9, // 7: baepo.api.v1.NodeControllerClientEvent.MachineStateChange.timestamp:type_name -> google.protobuf.Timestamp
	1, // 8: baepo.api.v1.NodeControllerService.Events:input_type -> baepo.api.v1.NodeControllerClientEvent
	0, // 9: baepo.api.v1.NodeControllerService.Events:output_type -> baepo.api.v1.NodeControllerServerEvent
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_baepo_api_v1_node_controller_proto_init() }
func file_baepo_api_v1_node_controller_proto_init() {
	if File_baepo_api_v1_node_controller_proto != nil {
		return
	}
	file_baepo_api_v1_node_controller_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeControllerServerEvent_Register)(nil),
		(*NodeControllerServerEvent_PingEvent)(nil),
	}
	file_baepo_api_v1_node_controller_proto_msgTypes[1].OneofWrappers = []any{
		(*NodeControllerClientEvent_Register)(nil),
		(*NodeControllerClientEvent_StatsEvent)(nil),
		(*NodeControllerClientEvent_MachineStateChangeEvent)(nil),
	}
	file_baepo_api_v1_node_controller_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_api_v1_node_controller_proto_rawDesc), len(file_baepo_api_v1_node_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baepo_api_v1_node_controller_proto_goTypes,
		DependencyIndexes: file_baepo_api_v1_node_controller_proto_depIdxs,
		MessageInfos:      file_baepo_api_v1_node_controller_proto_msgTypes,
	}.Build()
	File_baepo_api_v1_node_controller_proto = out.File
	file_baepo_api_v1_node_controller_proto_goTypes = nil
	file_baepo_api_v1_node_controller_proto_depIdxs = nil
}
