// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: baepo/api/v1/user.proto

package apiv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Admin         bool                   `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,7,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_baepo_api_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type UserMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMeResponse) Reset() {
	*x = UserMeResponse{}
	mi := &file_baepo_api_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMeResponse) ProtoMessage() {}

func (x *UserMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baepo_api_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMeResponse.ProtoReflect.Descriptor instead.
func (*UserMeResponse) Descriptor() ([]byte, []int) {
	return file_baepo_api_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserMeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_baepo_api_v1_user_proto protoreflect.FileDescriptor

const file_baepo_api_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x17baepo/api/v1/user.proto\x12\fbaepo.api.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05admin\x18\x05 \x01(\bR\x05admin\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fworkspace_id\x18\a \x01(\tR\vworkspaceId\"8\n" +
	"\x0eUserMeResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.baepo.api.v1.UserR\x04user2I\n" +
	"\vUserService\x12:\n" +
	"\x02Me\x12\x16.google.protobuf.Empty\x1a\x1c.baepo.api.v1.UserMeResponseB<Z:github.com/baepo-cloud/baepo-proto/go/baepo/api/v1;apiv1pbb\x06proto3"

var (
	file_baepo_api_v1_user_proto_rawDescOnce sync.Once
	file_baepo_api_v1_user_proto_rawDescData []byte
)

func file_baepo_api_v1_user_proto_rawDescGZIP() []byte {
	file_baepo_api_v1_user_proto_rawDescOnce.Do(func() {
		file_baepo_api_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baepo_api_v1_user_proto_rawDesc), len(file_baepo_api_v1_user_proto_rawDesc)))
	})
	return file_baepo_api_v1_user_proto_rawDescData
}

var file_baepo_api_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_baepo_api_v1_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: baepo.api.v1.User
	(*UserMeResponse)(nil),        // 1: baepo.api.v1.UserMeResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_baepo_api_v1_user_proto_depIdxs = []int32{
	2, // 0: baepo.api.v1.User.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: baepo.api.v1.UserMeResponse.user:type_name -> baepo.api.v1.User
	3, // 2: baepo.api.v1.UserService.Me:input_type -> google.protobuf.Empty
	1, // 3: baepo.api.v1.UserService.Me:output_type -> baepo.api.v1.UserMeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_baepo_api_v1_user_proto_init() }
func file_baepo_api_v1_user_proto_init() {
	if File_baepo_api_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baepo_api_v1_user_proto_rawDesc), len(file_baepo_api_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baepo_api_v1_user_proto_goTypes,
		DependencyIndexes: file_baepo_api_v1_user_proto_depIdxs,
		MessageInfos:      file_baepo_api_v1_user_proto_msgTypes,
	}.Build()
	File_baepo_api_v1_user_proto = out.File
	file_baepo_api_v1_user_proto_goTypes = nil
	file_baepo_api_v1_user_proto_depIdxs = nil
}
